### ISSUE TITLE
Feature: a one-liner version of newlines.alwaysBeforeElseAfterCurlyIf=true

### ISSUE THREAD

**Issue by kitbellew** [scalameta/scalafmt#1043] opened 2017-09-11 23:35 UTC
This template is a guideline, not a strict requirement.
- **Version**: 1.2.0
- **Integration**: CLI
- **Configuration**:
```
style = default
maxColumn = 100
danglingParentheses = true

align = none
align.tokens = []
align.openParenCallSite = false

newlines.alwaysBeforeTopLevelStatements = true
newlines.sometimesBeforeColonInMethodReturnType = false
newlines.alwaysBeforeCurlyBraceLambdaParams = true
newlines.afterImplicitKWInVerticalMultiline = true
newlines.beforeImplicitKWInVerticalMultiline = true

runner.fatalWarnings = true
runner.optimizer.forceConfigStyleOnOffset = 50
runner.optimizer.forceConfigStyleMinArgCount = 5

rewrite.rules = [ExpandImportSelectors, PreferCurlyFors]
```

## Steps

I ran scalafmt like this:

```bash
scalafmt
```

## Problem

Input is
```scala
      if ('0' <= ch && ch <= '9') { ch - '0' }
      else if ('A' <= ch && ch <= 'F') { ch - 'A' + 10 }
      else if ('a' <= ch && ch <= 'f') { ch - 'a' + 10 }
      else { -1 }
```

Scalafmt formats code like this:
```scala
      if ('0' <= ch && ch <= '9') { ch - '0' } else if ('A' <= ch && ch <= 'F') { ch - 'A' + 10 } else if ('a' <= ch && ch <= 'f') {
        ch - 'a' + 10
      } else { -1 }
```

## Expectation

I would like the formatted output to look either exactly like the input, or like this:
```scala
      if ('0' <= ch && ch <= '9') {
        ch - '0'
      } else if ('A' <= ch && ch <= 'F') {
        ch - 'A' + 10
      } else if ('a' <= ch && ch <= 'f') {
        ch - 'a' + 10
      } else {
        -1
      }
```
but definitely not the way it was chosen.

**Comment by olafurpg** [comment] 2018-05-12 09:47
Thanks for reporting! This is a duplicate of https://github.com/scalameta/scalafmt/issues/271, I agree the formatted output is not good.

Note that when given
```scala
    if ('0' <= ch && ch <= '9') {
        ch - '0'
      } else if ('A' <= ch && ch <= 'F') {
        ch - 'A' + 10
      } else if ('a' <= ch && ch <= 'f') {
        ch - 'a' + 10
      } else {
        -1
      }
```

Scalafmt leaves the code unchanged.

**Closed by olafurpg** 2018-05-12 09:47 UTC

**Comment by olafurpg** [comment] 2018-05-13 19:04
FYI I opened #1180 forcing a line break for if/else bodies that are blocks so that the formatted output matches expected output in this ticket. No need to manually insert line breaks :)
