### ISSUE TITLE
aligning for comprehension

### ISSUE THREAD

**Issue by okouyad** [scalameta/scalafmt#4175] opened 2024-08-21 14:45 UTC
## Problem

Using scala fmt i am trying to align the arrow of for-comprehension across blankline to so i can have groups in it. e.g.

```
for {
  x     <- List(1) // true for alignment enumerator
  yyy <- List(2)

  z <- List(3)
} yield x ** yyy
```

## Expectation

I would like to have it this way

```
for {
  x     <- List(1) // true for alignment enumerator
  yyy <- List(2)

  z     <- List(3)
} yield x ** yyy
```

align.preset = more

does not align across blankline

is there a way to do this ?

**Comment by kitbellew** [comment] 2024-08-21 14:51
since this is not a bug report, i will close this. for questions, please use discord -- after reading documentation on configuration parameters.

**Closed by kitbellew** 2024-08-21 14:51 UTC

**Comment by okouyad** [comment] 2024-08-21 16:39
That works. I have open the question there. I have red the documentation extensively, but could not figure out how to do it.
