### ISSUE TITLE
Incorrect indentation of code blocks within XML literals

### ISSUE THREAD

**Issue by DylanArnold** [scalameta/scalafmt#1882] opened 2020-04-16 06:21 UTC
I'm using [Binding.scala](https://github.com/ThoughtWorksInc/Binding.scala) framework and am having trouble formatting code blocks inside nested HTML literals. 

If I write deeply nested HTML and then include a code block, Scalafmt will not keep the correct indentation of the code block.

- **Version**: 2.5.0-RC1
- **Configuration**:
```
version=2.5.0-RC1
align = none
maxColumn = 120
continuationIndent.callSite = 2
continuationIndent.defnSite = 2
continuationIndent.extendSite = 2
```

The following examples are simplified and exclude annotations used in real [Binding.scala](https://github.com/ThoughtWorksInc/Binding.scala) code.

All examples are run using this command: `scalafmt --config .scalafmt.conf --stdout Example.scala`

### Example1
**Input:**
```scala
object Example1 {
  def apply() = {
    <div>
    <div>
    <div>
    </div>
    </div>
    </div>
  }
}
```

**Output:**

Example 1 output matches input.

**Notes:**

This examples contains 3 nested HTML elements and illustrates that there is no formatting of HTML by Scalafmt. It possibly could help to format by indenting inner elements based on element nesting level, however this isn't a critical issue, possibly more of a nice to have. It may be necessary for Scalafmt to be aware of element nesting level to correctly indent deeply nested code blocks.

**Expected output if Scalafmt were to format based on nesting level**:
```scala
object Example1 {
  def apply() = {
    <div>
      <div>
        <div>
        </div>
      </div>
    </div>
  }
}
```

### Example2
**Input:**

```scala
object Example2 {
  def apply() = {
    <div>
      <div>
        <div>
          <h1>Heading</h1>
          {
            val x = "stuff"
            <div>{x}</div>
          }
        </div>
      </div>
    </div>
  }
}
```

**Output:**

```scala
object Example2 {
  def apply() = {
    <div>
      <div>
        <div>
          <h1>Heading</h1>
          {
      val x = "stuff"
      <div>{x}</div>
    }
        </div>
      </div>
    </div>
  }
}
```

**Notes:**

This illustrates a nested code block. Scalafmt shifts some of the code back to a smaller indentation. I would expect the original indentation to be kept. 

### Example 3
**Input:**

```scala
object Example3 {
  def apply() = {
    <div>
      <div>
        <div>
          <h1>Heading</h1>
    {
      val x = "stuff"
      <div>{x}</div>
    }
        </div>
      </div>
    </div>
  }
}
```

**Output:**

Example 3 output matches input.

**Notes:**

This example contains a code block which is nested too far left. It illustrates that Scalafmt is happy with this nesting level, as it is at the correct nesting level for a block contained inside the `apply` method. I would expect the code block to be indented further to the right to respect the nesting level of the parent HTML element (to match the Example 2 input).

### Example 4
**Input:**

```scala
object Example4 {
  def apply() = {
    <div>
    {
      <div>
      {
        <div>
          <h1>Heading</h1>
        {
          val x = "stuff"
          <div>{x}</div>
        }
        </div>
      }
      </div>
    }
    </div>
  }
}
```

**Output:**

Example 4 output matches input.

**Notes:**

This illustrates a partial workaround to get the inner most code block to indent correctly, however it results in a lot of extra braces and requires less than ideal indentation of the code block. You have to shift the code block left to make it work. Ideally the code block would be shifted right, aligned with the `<h1>Heading</h1>` element above it (as in Example 2 input).

**Comment by poslegm** [comment] 2020-04-16 15:11
Hello!

scalafmt doesn't format XML literals. Reason described [here](https://github.com/scalameta/scalafmt/issues/662#issuecomment-298190421). We can revise it but anyway example 1 is not a bug.

What about formatting code _inside_ literals: yes, examples 2 and 3 are bugs (reproduces in v2.0.0).

**Comment by DylanArnold** [comment] 2020-04-16 23:10
Great thanks for the reply. That makes sense.

Please let me know if you need someone to work on this. I don't understand what is required to fix it and may need some help, but I'm willing to attempt a PR if needed.

**Comment by kitbellew** [comment] 2020-06-01 16:44
@DylanArnold given that scalafmt will preserve the space outside of scala code, that means the position of the opening brace relative to preceding xml is fixed, and so is the position of the closing brace relative to subsequent xml.

for instance, if the input had been
```
  def foo = {
    ...
          <foo>
            <bar>...</bar> { // start
    // scala code
    } </foo> // end
    ...
  }
```
then you can only change the indentation of _scala code_ and _end_ lines.

so far, they are consistent with the scala code outside of xml. sounds like you'd prefer to indent them relative to inner xml. so, in the example above, which? the only option is `<bar>`, which is what precedes the opening `{`, but that would also be incorrect.

thoughts?

**Comment by DylanArnold** [comment] 2020-06-03 04:03
@kitbellew Thanks for your reply, I think I understand.

Given your example I believe it is acceptable and may make most sense to indent relative to `<bar>` as you say. This should satisfy the space preservation rule and when writing HTML where I believe the rule matters less, it can be left up to the programmer to move `</foo>` to a new line themselves.

```scala
def foo = {
  ...
        <foo>
          <bar>...</bar> { // start
            // scala code
          } </foo> // end
  ...
}
```

I'll try to list a few examples given what I understand could be valid and fits into how Scalafmt works in general.

**Input 1:**
```scala
<foo>
  <bar>{
// Scala code
}</bar>
</foo>
```

**Output 1:**
```scala
<foo>
  <bar>{
    // Scala code
  }</bar>
</foo>
```

**Input 2:**
```scala
<foo>
  <bar>
    {
  // Scala code
  }
  </bar>
</foo>
```

**Output 2:**
```scala
<foo>
  <bar>
    {
      // Scala code
    }
  </bar>
</foo>
```

**Input 3:**
```scala
<foo>
  <bar>
  {
// Scala code
}
  </bar>
</foo>
```

**Output 3:**
```scala
<foo>
  <bar>
  {
    // Scala code
  }
  </bar>
</foo>
```

**Input 4:**
```scala
<foo>
  <bar baz={
// Scala code
}></bar>
</foo>
```

**Output 4:**
```scala
<foo>
  <bar baz={
    // Scala code
  }></bar>
</foo>
```

**Input 5:**
```scala
<foo>
  <bar>{ /* Long scala code */ }</bar>
</foo>
```

**Output 5:**
```scala
<foo>
  <bar>{
    /* Long scala code */
  }</bar>
</foo>
```

**Input 6:**
```scala
<foo>
  <bar baz={ /* Long scala code */ }></bar>
</foo>
```

**Output 6:**
```scala
<foo>
  <bar baz={
    /* Long scala code */
  }></bar>
</foo>
```

One final note regarding formatting of attributes like `baz` above. I'm not sure how this should format if there are multiple attributes with Scala code. I guess possibly the closing braces of other attributes could also align in the same way with `<bar>`.

**Closed** 2020-06-15 11:25 UTC
Labels: bug, ugly
