### ISSUE TITLE
Support Scala 3

### ISSUE THREAD

**Issue by tgodzik** [scalameta/scalafmt#2216] opened 2020-10-05 06:57 UTC
Thanks to https://github.com/scalameta/scalameta/pull/2104 and some previous PRs we should be able now to start work on formatting Scala 3 code.  This might bit of work on top of the parser, but I was thinking of coordinating the efforts via this issue.

The list of things we need to support or check:
- [x] enums https://github.com/scalameta/scalafmt/pull/2262 https://github.com/scalameta/scalafmt/pull/2283
- [x] extension methods https://github.com/scalameta/scalafmt/pull/2298
- [x] given definitions https://github.com/scalameta/scalafmt/pull/2332 
- [x] given export https://github.com/scalameta/scalafmt/pull/2331
- [x] given patterns `case a @ given Context =>` https://github.com/scalameta/scalafmt/pull/2327
- [x] given imports `import a.{given Context[_]}` https://github.com/scalameta/scalafmt/pull/2327 
- [x] using -  https://github.com/scalameta/scalafmt/pull/2284
- [x] export clause (`export a.b.{ ... }`) https://github.com/scalameta/scalafmt/pull/2329
- [x] macros/quote/splice (https://github.com/scalameta/scalafmt/pull/2286)
- [x] macro patterns https://github.com/scalameta/scalafmt/pull/2316
- [x] inline and transparent modifier https://github.com/scalameta/scalafmt/pull/2324
- [x] inline if (`inline if (a > b) a else b`) https://github.com/scalameta/scalafmt/pull/2353 
- [x] inline match https://github.com/scalameta/scalafmt/pull/2353
- [x] match types (`type List[X] = X match { ... }`) https://github.com/scalameta/scalafmt/pull/2309
- [x] match chaining and `.match` syntax https://github.com/scalameta/scalafmt/pull/2386
- [x] extending multiple traits with coma (`trait C extends A, B`) https://github.com/scalameta/scalafmt/pull/2326
- [x] trait parameters (`trait X(val i: Int`) https://github.com/scalameta/scalafmt/pull/2295
- [x] ~~super trait~~ **(removed in 3.0.0-M2)**
- [x] open classes (PR https://github.com/scalameta/scalafmt/pull/2285)
- [x] infix modifier https://github.com/scalameta/scalafmt/pull/2325
- [x] derivation (`class X derives Eql`)  https://github.com/scalameta/scalafmt/pull/2371
- [x] opaque type (`opaque type Logarithm = Double`) https://github.com/scalameta/scalafmt/pull/2330  
- [x] intersection / union types `(A & B)` `(A | B)` https://github.com/scalameta/scalafmt/pull/2340
- [x] type lambda (`[X, Y] =>> Map[Y, X]`) https://github.com/scalameta/scalafmt/pull/2339
- [x] polymorphic function types (`val a: [X] => Y => Z`) https://github.com/scalameta/scalafmt/pull/2338 
- [x] ~~named type arguments (`f[A = Int]()`)~~ most likely postponed until 3.1
- [x] type wildcard changed (`List[_] -> List[?]`) https://github.com/scalameta/scalafmt/pull/2295
- [x] statement `type T` https://github.com/scalameta/scalafmt/pull/2295
- [x] context functions (`type Executable[T] = ExecutionContext ?=> T`) https://github.com/scalameta/scalafmt/pull/2308
- [x] dependent function types `val extractor: (e: Entry) => e.Key = extractKey` https://github.com/scalameta/scalafmt/pull/2337 
- [x] changed vararg splices https://dotty.epfl.ch/docs/reference/changed-features/vararg-splices.html  https://github.com/scalameta/scalafmt/pull/2368
- [x] `=>` replaced with `as` for import renames https://github.com/scalameta/scalafmt/pull/2366
- [x] import all with `*`  https://github.com/scalameta/scalafmt/pull/2367
- [x] changed extensions to contain multiple using and allowed for type params in defs  https://github.com/scalameta/scalafmt/pull/2369

Optional braces:
- [x] configurable indentation for Scala 3 https://github.com/scalameta/scalafmt/pull/2401
- [x] blocks starting with keyword:
```
=  =>  ?=>  <-  catch  do  else  finally  for
if  match  return  then  throw  try  while  yield
```
- [x] blocks starting after `)` - extension methods and if clauses https://github.com/scalameta/scalafmt/pull/2406
- [x] templates starting with `:` - it should work with extends which means we need to update logic looking for curly braces probably https://github.com/scalameta/scalafmt/pull/2406
- [x] given definitions starting with `with` https://github.com/scalameta/scalafmt/pull/2406
- [x] end marker https://github.com/scalameta/scalafmt/pull/2406
- [x] match case indentation https://github.com/scalameta/scalafmt/pull/2411

Additional rewrite rules:
- [x] wildcard imports from `_` to `*`
- [x] `=>` to `as` for renamed imports
- [x] old varargs splices syntax to new one
- [x] braces to no braces
- [x] ~no braces to braces~ for now it is recommended to use `-no-indent` flag for the compiler. If needed we can also create an additional rule here. Some history on why this is difficult https://github.com/scalameta/scalafmt/issues/2019

Configuration:
- [x] allow different dialect for a specific subset of files https://scalameta.org/scalafmt/docs/configuration.html#fileoverride

**Comment by kpbochenek** [comment] 2020-10-05 13:16
List of dotty features introduced in parser: https://github.com/scalameta/scalameta/issues/2022

**Comment by kitbellew** [comment] 2020-10-05 14:54
> Thanks to [scalameta/scalameta#2104](https://github.com/scalameta/scalameta/pull/2104) and some previous PRs we should be able now to start work on formatting Scala 3 code. This might bit of work on top of the parser, but I was thinking of coordinating the efforts via this issue.

i can definitely help review 😀

please don't forget to abide by newline rules set by `newlines.source` (must ignore incoming newlines for `fold` and `unfold`) and to add plenty of tests in `newlines/classic|keep|fold|unfold.stat`.

> * [ ]  enums
looks like class

> * [ ]  givens
a bit like def

> * [ ]  using
implicit?

> * [ ]  new modifiers - super, transparent
should not forget the SortModifiers rewrite rule. inline, too?

> * [ ]  export
just like import

> * [ ]  macros
looks like just supporting `'` in front of `{` and `[`?

> * support optional braces, which would also include the `end` marker.
detection of nesting should be in the meta parser, no? ideally, it should be handled in the same rules as LeftBrace and RightBrace, which would set indentation.

**Comment by MichalBednarz** [comment] 2020-11-09 11:49
I have just discussed this issue with @tgodzik and I am going to start working on it.

**Comment by tgodzik** [comment] 2020-11-09 11:51
> I have just discussed this issue with @tgodzik and I am going to start working on it.

That's right. Michał has some time to spare currently and he will be helping me out with making Scala 3 working with scalafmt.

**Comment by tgodzik** [comment] 2020-12-02 21:17
I updated the list of things to work on. Some of it might be quick while some might require a bit more work. I mostly copied over the list from https://github.com/scalameta/scalameta/issues/2022, but removed anything that should work without issue. If anyone notices anything missing feel free to update it.

**Comment by unkarjedy** [comment] 2021-03-04 10:29
Looks like ticket
[Indent `yield` at same level as `for` when using parentheses](#592) 
should be reviewed in the context of Scala 3 formatting

Scala 3 [new control syntax](http://dotty.epfl.ch/docs/reference/other-new-features/control-syntax.html) supports for enumerators without braces/parens:
```scala3
for
  x <- 0 to 2
  y <- 0 to 2
yield
  println(s"Hello $x")
  x * 2
```

Looks like the most logical place for `yield` is as shown in the example (same level with for).
So `for` and `yield` will be at the same level, even if the execution level is different.
(see comment https://github.com/scalameta/scalafmt/issues/592#issuecomment-261523331)
Property "for & yield should be at different levels" would be broken anyway.
So, IMO It would be nice to have a consistency in `yield` indent between "single line enumerators" and "multi-line enumerators":
```scala3
for x <- 0 to 2
yield x * 2  // NOTE: yield is NOT intended as in other examples

for
  x <- 0 to 2
yield x * 2

for
  x <- 0 to 2
  y <- 0 to 2
yield x * 2

for
  x <- 0 to 2
  y <- 0 to 2
yield
  println(s"Hello $x")
  x * 2
```
VS
```scala3
for x <- 0 to 2
  yield x * 2 // NOTE: yield is indented

for
  x <- 0 to 2
yield x * 2

for
  x <- 0 to 2
  y <- 0 to 2
yield x * 2

for
  x <- 0 to 2
  y <- 0 to 2
yield
  println(s"Hello $x")
  x * 2
```

If so, looks like it also would make sense to preserve some consistency with Scala 2 and backport this to Scala2 formatting
 (probably with some setting)

BTW, [scala3 reference page](http://dotty.epfl.ch/docs/reference/other-new-features/control-syntax.html) uses such formatting 
(though it's not a strong argument)
![image](https://user-images.githubusercontent.com/3989292/109950031-25e83380-7ced-11eb-8d26-1dd6f2b35015.png)

**Comment by unkarjedy** [comment] 2021-03-05 07:54
(sorry, there ^ was a wrong link to https://github.com/scalameta/scalafmt/issues/592, updated)

**Comment by unkarjedy** [comment] 2021-03-05 09:40
BTW, regarding this part of the comment
>yield is logically inside each iteration of for

Each subsequent enumerator is logically inside each iteration of the previous enumerator.
But still in Scala 2 we do not format it as:
```scala
for {
  x <- 0 to 2
    y <- 0 to 2
      z <- 0 to 2
} yield x * 2
```

**Comment by hejfelix** [comment] 2021-04-04 18:53
Is the issue description up to date? Missing scalafmt is the biggest pain in Scala 3 IMHO.

**Comment by tgodzik** [comment] 2021-04-05 17:00
> Is the issue description up to date? Missing scalafmt is the biggest pain in Scala 3 IMHO.

It is, we are keeping it up to date. the biggest missing part is currently optional braces, which is the next thing I plan to work on.

**Comment by kitbellew** [comment] 2021-04-05 17:03
@tgodzik should we release an alpha for people to try if the majority of features are available, while you're working on significant indentation?

**Comment by kitbellew** [comment] 2021-04-05 17:22
> * [ ]  allow different dialect for a specific subset of files

@tgodzik would this not work: https://scalameta.org/scalafmt/docs/configuration.html#fileoverride

**Comment by tgodzik** [comment] 2021-04-05 17:25
> @tgodzik should we release an alpha for people to try if the majority of features are available, while you're working on significant indentation?

I think that is sensible, although I would enable the significant indentation feature in the dialect, so that it doesn't blow up for the users. Although, I would do it only if this would just leave the indented sections as is. I haven't yet checked that. I can take a look tomorrow (had a bit of a small but intensive family Easter :sweat_smile: ) .

> > * [ ]   allow different dialect for a specific subset of files
> 
> @tgodzik would this not work: https://scalameta.org/scalafmt/docs/configuration.html#fileoverride

Och yeah, that would work! I haven't found that option, thanks!

**Comment by tgodzik** [comment] 2021-04-07 20:28
The last thing we need to do here is the additional rewrite rules, but I think we should be able to release `3.0.0-RC1` version for the people to test it out? What do you think @kitbellew ? 

I can take care of the rewrite rules next week if unless anyone else want to tinker with it?

**Comment by kitbellew** [comment] 2021-04-07 21:25
> ... I think we should be able to release `3.0.0-RC1` version for the people to test it out? What do you think @kitbellew ?

go for it! if i remember correctly, it works best if you tag locally and push it. @poslegm saw some release builder anomalies when we tagged online, via https://github.com/scalameta/scalafmt/releases. after it's built, you should go to that page and publish the release notes using your previously set tag.

**Comment by mwzzhang** [comment] 2021-04-15 14:30
Any news on this so far? 2.7.5 (with runner.dialect = Dotty) kept dying on scala3 enum even with braces everywhere, never mind any sort of brace-less code.

Should I file a separate bug report for this or was this already fixed in master?

Cheers guys, love your work.

**Comment by tgodzik** [comment] 2021-04-15 14:34
There is some work needed, but I think we can release the RC version finally. If no one objects I will work on it within the enxt hour.

**Comment by tgodzik** [comment] 2021-04-15 16:43
3.0.0-RC-1 is out! You can test it out by using `runner.dialect = scala3` - some examples https://github.com/scalameta/metals/pull/2726

**Comment by kitbellew** [comment] 2021-04-15 17:00
> 3.0.0-RC-1 is out! You can test it out by using `runner.dialect = scala3` - some examples [scalameta/metals#2726](https://github.com/scalameta/metals/pull/2726)

if you had waited another day, would have been exactly 6 months since 2.7.5 :)

**Comment by djneades** [comment] 2021-04-15 20:27
It’s really great to see the progress on Scala 3 support. Unfortunately, I immediately ran into #2421 when trying 3.0.0-RC1.

**Comment by cchantep** [comment] 2021-04-17 14:08
Not supported : 

```scala
private given x: X = ???
```

Reformatted wrongly as:

```scala
private

given x: X = ???
```

**Comment by MichalBednarz** [comment] 2021-04-19 07:48
@cchantep could you please provide your scalafmt settings as well as the context of the above statement? I couldn't reproduce this behavior, it seems to be formatted correctly as a standalone statement regardless of maxColumn settings.

**Comment by cchantep** [comment] 2021-04-19 16:42
```
version = 3.0.0-RC1
runner.dialect = scala3

newlines.alwaysBeforeElseAfterCurlyIf = false
newlines.beforeMultilineDef = keep
newlines.topLevelStatements = [before]
newlines.beforeCurlyLambdaParams = multilineWithCaseOnly
newlines.afterCurlyLambdaParams = squash
newlines.implicitParamListModifierForce = [after]
newlines.avoidForSimpleOverflow = [tooLong]
newlines.avoidInResultType = true
newlines.sometimesBeforeColonInMethodReturnType = false

verticalMultiline.atDefnSite = true
verticalMultiline.arityThreshold = 10

spaces.inImportCurlyBraces = true

includeCurlyBraceInSelectChains = false
includeNoParensInSelectChains = false
optIn.breakChainOnFirstMethodDot = false

docstrings.style = Asterisk

literals.long=Upper
literals.float=Upper
literals.double=Upper
```

**Comment by keynmol** [comment] 2021-04-21 07:04
We've just tried it out on a project and it went off almost without a hitch, great work!

The one fun example is this:

```scala
❯ cat test.scala
import java.text.{CharacterIterator, StringCharacterIterator}

object Pattern:
  def test =
    val charIter = StringCharacterIterator("hello")
    var c = charIter.first()
    while (c != CharacterIterator.DONE)
      println(c)
      c = charIter.next()

@main def hello =
  Pattern.test

❯ cs launch scala3-compiler -- test.scala

❯ cat .scalafmt.conf
version = 3.0.0-RC1
runner.dialect = scala3

❯ cs launch scalafmt:3.0.0-RC1

❯ cat test.scala
import java.text.{CharacterIterator, StringCharacterIterator}

object Pattern:
  def test =
    val charIter = StringCharacterIterator("hello")
    var c = charIter.first()
    while (c != CharacterIterator.DONE)
      println(c)
    c = charIter.next()

@main def hello =
  Pattern.test

```

As you can see, after formatting the while loop is now non-terminating :) And this happened during macro expansion, so it was fun.

The compiler itself seems to consider both versions valid code and runs it: https://scastie.scala-lang.org/2Ahn4e0JRRiXqMJYm8vllg

**Comment by tgodzik** [comment] 2021-04-21 08:24
@keynmol that's because we haven't really accounted for old while syntax plus optional braces. It was only recently documented https://github.com/lampepfl/dotty/pull/12136, but essentially parser would treat it as a single statement `while`. Best to use new contruct `while ... do`, but we already fixed this one in the parser. I will most likely be included in RC2.

**Comment by keynmol** [comment] 2021-04-21 08:29
Thanks @tgodzik! I went to scastie exactly to check how the compiler treats it, as I wasn't sure how scalafmt is supposed to figure it out :)

**Comment by tgodzik** [comment] 2021-04-21 08:55
@cchantep it's an issue in the parser, fixing it here: https://github.com/scalameta/scalameta/pull/2295

Thanks for letting us know!

**Comment by kubukoz** [comment] 2021-04-21 09:13
I have more!

```
org.scalafmt.dynamic.exceptions.PositionExceptionImpl: /Users/jkoslowski/IdeaProjects/slang/src/main/scala/com/kubukoz/slang/parser/print.scala:18: error: outdent expected but case found
    case Expectation.FailWith(_, msg) => msged
    ^: /Users/jkoslowski/IdeaProjects/slang/src/main/scala/com/kubukoz/slang/parser/print.scala
org.scalafmt.dynamic.exceptions.PositionExceptionImpl: /Users/jkoslowski/IdeaProjects/slang/src/test/scala/com/kubukoz/slang/dsl.scala:30: error: ] expected but . found
    given Conversion[AppliedName, Expr.Apply[Id]] = _.toExpr
                                      ^: /Users/jkoslowski/IdeaProjects/slang/src/test/scala/com/kubukoz/slang/dsl.scala
org.scalafmt.dynamic.exceptions.PositionExceptionImpl: /Users/jkoslowski/IdeaProjects/slang/src/main/scala/com/kubukoz/slang/qualifier/Qualifier.scala:95: error: outdent expected but case found
      case Expr.FunctionDef(functionName, _, _) =>
      ^: /Users/jkoslowski/IdeaProjects/slang/src/main/scala/com/kubukoz/slang/qualifier/Qualifier.scala
org.scalafmt.dynamic.exceptions.PositionExceptionImpl: /Users/jkoslowski/IdeaProjects/slang/src/main/scala/com/kubukoz/slang/parser/parser.scala:100: error: outdent expected but case found
    case SourceFile(fileName, source) =>matted
    ^: /Users/jkoslowski/IdeaProjects/slang/src/main/scala/com/kubukoz/slang/parser/parser.scala
```

and this one seems more serious:

```
Router:2088 MISSING CASE:
[543]=>>                            TypeLambdaArrow
[544]                               Space
[550]Scoped                         Ident
org.scalafmt.cli.FailedToFormat: /Users/jkoslowski/IdeaProjects/slang/src/main/scala/com/kubukoz/slang/core/Scoped.scala
Caused by: org.scalafmt.Error$PreciseIncomplete: /Users/jkoslowski/IdeaProjects/slang/src/main/scala/com/kubukoz/slang/core/Scoped.scala:18: error: Unable to format file due to bug in scalafmt
  type Of[S] = [F[_]] =>> Scoped[F, S]
                      ^
	at org.scalafmt.Scalafmt$.$anonfun$doFormatOne$6(Scalafmt.scala:133)
	at scala.util.Success.flatMap(Try.scala:258)
	at org.scalafmt.Scalafmt$.$anonfun$doFormatOne$3(Scalafmt.scala:128)
	at scala.meta.parsers.Parsed.fold(Errors.scala:12)
	at scala.meta.parsers.Parsed.fold$(Errors.scala:11)
	at scala.meta.parsers.Parsed$Success.fold(Errors.scala:26)
	at org.scalafmt.Scalafmt$.doFormatOne(Scalafmt.scala:124)
	at org.scalafmt.Scalafmt$.doFormat(Scalafmt.scala:102)
	at org.scalafmt.Scalafmt$.formatCode(Scalafmt.scala:71)
	at org.scalafmt.Scalafmt$.format(Scalafmt.scala:52)
	at org.scalafmt.Scalafmt.format(Scalafmt.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.scalafmt.dynamic.ScalafmtReflect.format(ScalafmtReflect.scala:107)
	at org.scalafmt.dynamic.ScalafmtReflectConfig.format(ScalafmtReflectConfig.scala:121)
	at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$tryFormat$1(ScalafmtDynamic.scala:203)
	at scala.util.Try$.apply(Try.scala:213)
	at org.scalafmt.dynamic.ScalafmtDynamic.org$scalafmt$dynamic$ScalafmtDynamic$$tryFormat(ScalafmtDynamic.scala:188)
	at org.scalafmt.dynamic.ScalafmtDynamic$MySession.format(ScalafmtDynamic.scala:245)
	at org.scalafmt.cli.ScalafmtDynamicRunner$.handleFile(ScalafmtDynamicRunner.scala:114)
	at org.scalafmt.cli.ScalafmtDynamicRunner$.$anonfun$run$4(ScalafmtDynamicRunner.scala:62)
	at org.scalafmt.cli.ScalafmtDynamicRunner$.$anonfun$run$4$adapted(ScalafmtDynamicRunner.scala:60)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:974)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:971)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:160)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

config:

```
version = "3.0.0-RC1"
runner.dialect = scala3
maxColumn = 140
align.preset = some
align.tokens.add = [
  {code = "<-", owner = Enumerator.Generator}
]
align.multiline = true
align.arrowEnumeratorGenerator = true

newlines.topLevelStatements = [before, after]
newlines.implicitParamListModifierForce = [before]
newlines.topLevelStatementsMinBreaks = 2
continuationIndent.defnSite = 2
continuationIndent.extendSite = 2

optIn.breakChainOnFirstMethodDot = true
includeCurlyBraceInSelectChains = true
includeNoParensInSelectChains = true

rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  ExpandImportSelectors,
  PreferCurlyFors
]

runner.optimizer.forceConfigStyleMinArgCount = 3
danglingParentheses.defnSite = true
danglingParentheses.callSite = true
danglingParentheses.exclude = [
  "`trait`"
]
verticalMultiline.newlineAfterOpenParen = true
verticalMultiline.atDefnSite = true
```

source before: https://github.com/kubukoz/slang/tree/f061a3941228c55f931197896bf29e1d0ea82b12

source after: https://github.com/kubukoz/slang/tree/ef04c0c3272e7b80bb86b5c3107b8f213ac48673

**Comment by tgodzik** [comment] 2021-04-21 09:22
> outdent expected but case found
 
Those should already be fixed in the parser.

```
org.scalafmt.dynamic.exceptions.PositionExceptionImpl: /Users/jkoslowski/IdeaProjects/slang/src/test/scala/com/kubukoz/slang/dsl.scala:30: error: ] expected but . found
    given Conversion[AppliedName, Expr.Apply[Id]] = _.toExpr
                                      ^: /Users/jkoslowski/IdeaProjects/slang/src/test/scala/com/kubukoz/slang/dsl.scala
```

This one seems new.

The last one seems to be issue in Scalafmt itself. 

I will take a look, thanks!

**Comment by tgodzik** [comment] 2021-04-21 10:59
@kukuboz Both issues are addressed. We will most likely release Scalameta parser soon and update it here.

**Comment by kubukoz** [comment] 2021-04-21 12:04
You're on fire ;)

**Closed** 2021-04-29 08:12 UTC

**Comment by kubukoz** [comment] 2021-04-29 10:13
All my issues were solved in RC2!

**Comment by kubukoz** [comment] 2021-05-17 01:46
Looks like in 3.0.0-RC2 there's this:

```scala
lazy val elemInstances = summonAll[m.MirroredElemTypes]

inline m match
  case s: Mirror.SumOf[T]     => eqSum(s, elemInstances)
  case p: Mirror.ProductOf[T] => eqProduct(p, elemInstances)
```

formatted as

```scala
lazy val elemInstances = summonAll[m.MirroredElemTypes] inline
m match
  case s: Mirror.SumOf[T]     => eqSum(s, elemInstances)
  case p: Mirror.ProductOf[T] => eqProduct(p, elemInstances)
```

which breaks compilation :/

**Comment by tgodzik** [comment] 2021-05-17 14:38
That is already fixed, and will be available in RC3. I am trying to release new scalameta version as we speak and then we should be able to get RC3 for scalafmt

**Comment by kubukoz** [comment] 2021-05-17 15:03
Awesome!
