### ISSUE TITLE
rewrite - RedundantParens  - can break code

### ISSUE THREAD

**Issue by yurique** [scalameta/scalafmt#4217] opened 2024-09-04 21:00 UTC
## Configuration (required) ##

Please paste the **smallest** possible set of `.scalafmt.conf`
configuration parameters that reproduces the problem:
```
version = 3.8.3
runner.dialect = "scala213"
rewrite.rules = [RedundantParens]
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt --stdout fmt-test.scala`

## Steps

Given code like this:
```scala
object Test {
  val b: Boolean = ???
  (!b).booleanExtMethodReturningString()
}
```

## Problem

Scalafmt formats code like this:
```scala
object Test {
  val b: Boolean = ???
  !b.booleanExtMethodReturningString()
}
```

## Expectation

I would like the formatted output to look like this:
(note the parens around `!b` are preserved)
```scala
object Test {
  val b: Boolean = ???
  (!b).booleanExtMethodReturningString()
}
```

## Workaround

Remowing `RedundantParens` from the rewrite rules obviously helps :) 

## Notes

`.` has higher precedence than `!` thus this change (removing the parens) changes the program.

**Comment by kitbellew** [comment] 2024-09-04 21:15
thank you for reporting. it's a duplicate of two other submissions one of which is intentionally kept open to indicate that it's a known problem.

**Closed by kitbellew** 2024-09-04 21:15 UTC

**Comment by yurique** [comment] 2024-09-04 21:50
thank you for such a quick reply! 
sorry I didn't think to check if it was already reported :)
