### ISSUE TITLE
RedundantParens not working properly with boolean `!` unary operator

### ISSUE THREAD

**Issue by acote-coveo** [scalameta/scalafmt#4142] opened 2024-08-06 15:08 UTC
## Configuration (required) ##

Please paste the **smallest** possible set of `.scalafmt.conf`
configuration parameters that reproduces the problem:
```
version = 3.8.3
runner.dialect = scala212

rewrite.rules = [RedundantParens]
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt`

## Steps

Given code like this:
```scala
object Test {
  
  val boolean = true
  
  println(s"${(!boolean).toString}")
}
```

## Problem

Scalafmt formats code like this:
```scala
object Test {

  val boolean = true

  println(s"${!boolean.toString}")
}
```

## Expectation

I would like the formatted output to look like this:
```scala
object Test {
  
  val boolean = true
  
  println(s"${(!boolean).toString}")
}
```

## Workaround

I can workaround that by either reverting the version (to 3.8.2) or removing the `RedundantParens` rewrite rules.

**Comment by kitbellew** [comment] 2024-08-06 21:33
duplicate of #4117.

**Closed** 2024-10-11 21:28 UTC
