### ISSUE TITLE
Parser breaks on code calling generic apply method

### ISSUE THREAD

**Issue by ctoomey** [scalameta/scalafmt#1050] opened 2017-09-21 01:18 UTC
This template is a guideline, not a strict requirement.
- **Version**: 1.2.0
- **Integration**: CLI
- **Configuration**:
```
style = default
```

## Steps

I ran scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt issues a warning and doesn't format files containing `_[`, e.g. `query.getRows().map(_[String]("code"))`. The warning is "error: ) expected but [ found".

## Expectation

Since this is valid syntax it should not break on it.

## Workaround

I've found that it can be worked around by making the `apply` function explicit, e.g. `query.getRows().map(_.apply[String]("code"))`.

**Comment by xeno-by** [comment] 2017-09-21 01:21
This error is caused by a bug in the parser that we have in Scalameta. We've fixed that one in Scalameta 2.0, so the upgrade should solve this issue.

**Comment by olafurpg** [comment] 2017-09-21 10:14
Correct, this parser bug is fixed in scalameta v2.0, gonna label this as a duplicate of #975

**Comment by olafurpg** [comment] 2017-09-21 10:14
Duplicate of #975

**Closed by olafurpg** 2017-09-21 10:14 UTC
