### ISSUE TITLE
Formatting Scala 3 `while` loops messes with semantics

### ISSUE THREAD

**Issue by armanbilge** [scalameta/scalafmt#2807] opened 2021-10-19 20:38 UTC
https://github.com/typelevel/spire/pull/1084/commits/2a9ef8e7f407765e7ca7fe2120e03efa5f022187#diff-4cfd2338c236612e3ba17f6ddfc0b0fb1f77c149ea00adf96eb9da509c4a3d52L105-L128

@keynmol tells me this was previously encountered, and supposedly fixed.

Personally I don't mind if scalafmt can't handle these specific situations, but it would be nice if it could stop fatally or at least issue a warning.

In any case, I've switched these to `while ... do` syntax.

**Comment by kitbellew** [comment] 2021-10-19 23:52
looks like a duplicate of #2790

**Closed by kitbellew** 2021-10-19 23:52 UTC
