### ISSUE TITLE
How to ignore long imports?

### ISSUE THREAD

**Issue by arbitrary-dev** [scalameta/scalafmt#2289] opened 2020-12-09 12:40 UTC
## Problem

Scalafmt formats code like this:
```diff
-import very.very.very.long.line.with.{lots, of, additional, items}
+import very.very.very.long.line.with.{
+  lots,
+  of,
+  additional,
+  items
+}

But Scalafix and Idea's import optimizers return them back to one-liner.
```

## Expectation

I would like to have a setting which would allow to ignore or don't break long imports into multiline.

**Comment by kitbellew** [comment] 2021-03-31 23:04
Duplicate of #457.

**Closed** 2021-03-31 23:11 UTC
Labels: documentation
