### ISSUE TITLE
[FEATURE REQUEST] Apply scalafmt on diffs only

### ISSUE THREAD

**Issue by amsayk** [scalameta/scalafmt#1120] opened 2018-03-12 14:51 UTC
Hi,

Is it possible to add functionality to format only code that has changed in current commit?

Something similar to what `https://github.com/nrwl/precise-commits` does.

I am willing to contribute towards this feature, with a little guidance of course.

Thanks.

**Comment by olafurpg** [comment] 2018-03-12 15:05
Thanks for reporting! This is a duplicate of #244. I did spend quite a lot of time trying to get this functionality working but struggled to make it work well for a long tail of weird/unusual diffs. Scala programs tend to have large expressions and it's not easy to stop and resume the formatting algorithms at any given offset while preserving logical indentation and other important details. For example, one case I struggled with was long "select chains"

```
List(1)
  .map(x => ... )
  .filter(..)
  .collect { case x =>
    // large block of code here
  }
```
Scalafmt is quite opinionated about how chains like that are formatting so it's not trivial to take any random diff inside of that chain and only run scalafmt on the characters that changed. Another example where the naive solution of formatting the entire file and selecting only the subset that changed produces unexpected behavior https://github.com/ensime/ensime-server/pull/1619#issuecomment-256277008

The lack of this feature has not been a big problem in my experience as long as scalafmt is enabled for your entire project. I understand that's not easy to retrofit on a large existing codebase. However, I know several organization with multi-million line Scala codebases have bitten the bullet and migrated large chunks of code to scalafmt.

**Comment by olafurpg** [comment] 2018-03-12 15:05
Closing as duplicate of #244

**Closed by olafurpg** 2018-03-12 15:05 UTC

**Comment by amsayk** [comment] 2018-03-12 16:44
Ok fair enough. I will just go with the --diff option.

Thanks.

**Comment by amsayk** [comment] 2018-03-14 11:13
Hi @olafurpg,

How about we format the entire file but then restore everything outside the range.

What do you think?

**Comment by sjrd** [comment] 2018-03-14 12:06
One possibility would be to always expand the range to the smallest enclosing item (statement or expression) of a `{}` block. Then always put that item on a dedicated line, assume that the indentation of the `{` is correct, and derive the indentation of the item from that (i.e., +2), and format the item using the given indentation.

**Comment by olafurpg** [comment] 2018-03-14 12:48
That is the approach I tried @sjrd and it worked pretty great for a wide range of situations but I struggled to make it work in for example long select chains

```scala
myList.collect { case ... => ... }
  .foo(a => ...)
  .bar { x =>
    ...
  }
   .qux {
   case (y, ..., Vector(a, b, c)) =>
      println(1)
  }
```

It requires heuristics to infer the correct indentation and non-trivial amount of special handling that I deemed it not worth it eventually. The property I wanted to achieve was that `scalafmt --diff < git diff HEAD~N` would produce no diff for any `N` in a codebase where scalafmt was enforced at every commit.
