### ISSUE TITLE
try/finally forces premature wrapping?

### ISSUE THREAD

**Issue by dwijnand** [scalameta/scalafmt#805] opened 2017-03-09 14:15 UTC
- **Version**: 0.5.8
- **Integration**: CLI
- **Configuration**:
```
maxColumn = 112
```

## Steps

I ran scalafmt like this:

```bash
scalafmt -c .scalafmt.conf -i -f Foo.scala
```

## Problem

Scalafmt formats code like this:
```scala
object Foo {
  private[this] def andClose[A <: java.io.Closeable, B](x: A)(f: A => B): B =
    try f(x)
    finally x.close()
}
```

## Expectation

I would like the formatted output to look like this:
```scala
object Foo {
  private[this] def andClose[A <: java.io.Closeable, B](x: A)(f: A => B): B = try f(x) finally x.close()
}
```

## Workaround

n/a

## Notes

For clarity, that line is not longer than 112 columns.

**Comment by dwijnand** [comment] 2017-03-09 14:35
Yeah, something's up with `try`, this one is even more severe. Not even close to 112 columns:

## Problem

```scala
object Foo {
  def f = {
    def g = {
      val exists = try new File(resolved).exists
      catch { case _: IllegalArgumentException => false }
    }
  }
}
```

## Expectation

```scala
object Foo {
  def f = {
    def g = {
      val exists = try new File(resolved).exists catch { case _: IllegalArgumentException => false }
    }
  }
}
```

**Comment by olafurpg** [comment] 2017-03-11 19:05
I agree, this is was unexpected https://github.com/olafurpg/scalafmt/issues/805#issuecomment-285367819

I'm not convinced about putting try/finally on the same line however, scalafmt intentionally forces newlines around if/else try/catch even when it could fit on a single line. Please consider giving that
vertical space some love

**Comment by dwijnand** [comment] 2017-03-11 19:12
My vertical space is sacrosanct, as it is already otherwise in use for consecutive-line vertical-alignment! Wrapping prematurely throws that beauty away.

**Comment by olafurpg** [comment] 2018-05-14 14:06
I personally don't like single-line try/catch or try/finally. I am happy with the current behavior that scalafmt forces a break for catch/finally. There are some bugs related to the indentation for catch/finally, but those are already reported in other tickets.

Closing as "working as intended"

**Closed by olafurpg** 2018-05-14 14:06 UTC
Labels: router
