### ISSUE TITLE
Scalafmt has trouble with escaped quotes

### ISSUE THREAD

**Issue by seanmcl** [scalameta/scalafmt#1119] opened 2018-03-09 21:42 UTC
This template is a guideline, not a strict requirement.
- **Version**: 0.5
- **Integration**: IntelliJ
- **Configuration**:
```
maxColumn = 100
```

## Steps

Given code like this:
```scala
val argNames = args.map(v => s"\"${v.name}\"").mkString(", ")
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
val argNames = args.map(v => s"\" $ { v.name } \ "").mkString(", ")
```

## Expectation

I would like the formatted output to look like this:
```scala
val argNames = args.map(v => s"\"${v.name}\"").mkString(", ")
```

## Workaround
```scala
val argNames = args.map(v => s""""${v.name}"""").mkString(", ")
```

**Comment by olafurpg** [comment] 2018-05-13 18:02
Thanks for reporting! This seems like a duplicate of https://github.com/scalameta/scalafmt/issues/872 The issue was closed since the formatted output has surprisingly the same AST before and after

```
$ cat foo.scala
object Foo {
  val foo = 1
  s"\"${foo}\""       // original input
  s"\" $ { foo } \ "" // scalafmt output 
}
$ scalac -Xprint:parser foo.scala
...
    StringContext("\\").s().$(foo.$bslash(""));
    StringContext("\\").s().$(foo.$bslash(""))
```

It's clear from the compile errors that the string interpolation is not working as you'd expect it to
```scala
foo.scala:3: error: value $ is not a member of String
  s"\"${foo}\""
      ^
foo.scala:3: error: value \ is not a member of Int
  s"\"${foo}\""
            ^

foo.scala:4: error: value $ is not a member of String
  s"\" $ { foo } \ ""
       ^
foo.scala:4: error: value \ is not a member of Int
  s"\" $ { foo } \ ""
                 ^
```
So I believe scalafmt is working as intended.

**Closed by olafurpg** 2018-05-13 18:02 UTC
