### ISSUE TITLE
RedundantParens removes parens that are not redundant

### ISSUE THREAD

**Issue by agilesteel** [scalameta/scalafmt#4117] opened 2024-07-25 13:29 UTC
```
version = "3.8.3"
maxColumn = 100
rewrite.rules = [ RedundantParens ]
runner.dialect = scala213
```

## Steps

Given code like this:
```scala
object a {
  val b: Long = 1
}

(-a.b).toString
```

## Problem

Scalafmt formats code like this:
```scala
-a.b.toString
```
Parens are removed and the code doesn't compile with
```
value unary_- is not a member of String
```

## Expectation

I would like the formatted output to look like this:
```scala
(-a.b).toString // untouched
```

## Workaround

Revert to `v3.8.2` or disable formatting.

## Note

This also happens in Scala3.

**Comment by kitbellew** [comment] 2024-07-25 15:04
duplicate of #4116.

**Closed by kitbellew** 2024-07-25 15:04 UTC
