### ISSUE TITLE
No indentation for vals initialized with an expression using infix operator notation

### ISSUE THREAD

**Issue by hseeberger** [scalameta/scalafmt#997] opened 2017-07-10 05:49 UTC
This template is a guideline, not a strict requirement.
- **Version**: 1.1.0
- **Integration**: IntelliJ, neo-sbt-scalafmt
- **Configuration**:

```
style = defaultWithAlign

danglingParentheses        = true
indentOperator             = spray
maxColumn                  = 100
project.excludeFilters     = [".*\\.sbt"]
rewrite.rules              = [AsciiSortImports, RedundantBraces, RedundantParens]
spaces.inImportCurlyBraces = true
unindentTopLevelOperators  = true
```

## Problem

Scalafmt formats code like this:
```scala
  val foo =
  "abc" ++
  "def"

  def bar =
    "abc" ++
    "def"
```

## Expectation

I would like the formatted output to look like this:
```scala
  val foo =
    "abc" ++
    "def"

  def bar =
    "abc" ++
    "def"
```

So for `def` scalafmt works like expected, but for `val` it uses zero indentation after the line declaring the identifier.

Same happens for 
```
  val foo =
    "abc" split ""
```

But not for 
```
  val foo =
    "abc".split("")
```

So it seems to be related to infix operator notation.

**Comment by olafurpg** [comment] 2017-08-11 21:51
Duplicate of https://github.com/scalameta/scalafmt/issues/848 ?

**Comment by hseeberger** [comment] 2017-08-11 21:55
Hell yeah! Sorry for the noise.

**Comment by olafurpg** [comment] 2017-08-11 21:56
No worries, sorry for the slow response! Been away on holidays and struggling to keep up with all tickets :)

**Closed by olafurpg** 2017-08-11 21:56 UTC
