### ISSUE TITLE
`newlines.source = keep` (Scalafmt 3.7.1) and fewerBraces cause incorrect and non-idempotent formatting 

### ISSUE THREAD

**Issue by rmgk** [scalameta/scalafmt#3448] opened 2023-01-30 22:49 UTC
example code
```scala
//> using scala "3.3.0-RC2"

def Block(f: => Int): Int = f

def test(): String =
  Block:
    2 + 2
  .toString
```

config 
```
version = 3.7.1
runner.dialect = scala3
newlines.source = keep
```

format once
```scala
def test(): String =
  Block:
    2 + 2
    .toString
```

format twice:
```scala
def test(): String =
  Block:
    2 + 2
      .toString
```

`newlines.source = fold,unfold` are also broken with different results

Edit: my full example also seems to have the problem without setting `newlines.source`, but the minimal reproduction here does not seem to exhibit that 🤔

**Comment by kitbellew** [comment] 2023-01-31 13:50
@rmgk is it 3.3.0 or 3.7.1? i am a bit confused.

**Comment by tgodzik** [comment] 2023-01-31 14:02
I can reproduce it under `3.7.1`.

**Comment by kitbellew** [comment] 2023-02-06 13:27
@tgodzik @rmgk how should we solve this? continuation for chain requires main indentation. for fewer braces argument, it uses significant indentation.

the only clean way to allow this is to force fewer braces arguments to main + significant

**Comment by tgodzik** [comment] 2023-02-06 14:16
Actually, I think the main issue here is that the second example:
```
def test(): String =
  Block:
    2 + 2
    .toString
```
stops compiling

**Comment by kitbellew** [comment] 2023-02-06 15:00
> Actually, I think the main issue here is that the second example:
> 
> ```
> def test(): String =
>   Block:
>     2 + 2
>     .toString
> ```
> 
> stops compiling

what does that mean that it's the main issue? the right way to write this code is
```
Block:
     2 + 2
  .toString
```
as if it had really been
```
Block
  {
     2 + 2
  }
  .toString
```
anything else is either a different expression, or shouldn't compile.

**Comment by tgodzik** [comment] 2023-02-06 15:36
Yes, the first snippet is:
```scala
def test(): String =
  Block:
    2 + 2
  .toString
```

which means:
```scala
def test(): String =
  Block{
    2 + 2
  }.toString
```

but then we get:

```scala
def test(): String =
  Block:
    2 + 2
    .toString
```

which is:

```scala
def test(): String =
  Block:{
    2 + 2.toString
  }
```

so this changes the tree, or am I missing something?

**Comment by kitbellew** [comment] 2023-02-06 15:48
the reason it happens is because 2+2 was not indented, by the formatter, more than .toString, hence the next run results in a different expression. by default, significant is 3 and main is 2, so would have been fine but in this case significant looks to be set to 2 as well.

**Comment by tgodzik** [comment] 2023-02-06 16:50
Could we skip indenting the part after a block if the block is lacking `{}`?

**Comment by kitbellew** [comment] 2023-02-06 17:02
> Could we skip indenting the part after a block if the block is lacking `{}`?

that's not consistent with how we have done things. the chain continuation `.` never starts in the same position:
```
foo {
  2 + 2
} // comment
  .bar
foo {
  2 + 2
}.bar // still not the same as foo
// but not this
foo(
  2 + 2
)
.bar
```

**Comment by kitbellew** [comment] 2023-02-07 14:54
> > what does that mean that it's the main issue? the right way to write this code is
> > ```
> > Block:
> >      2 + 2
> >   .toString
> > ```
> 
> That example is not a valid Scala expression. A block with significant indentation must be followed by something that is at most as far indented as the indentation of the opening line. So the `.toString` above must start in the same column as the `B` of `Block`.

that's not what the rule says (https://docs.scala-lang.org/scala3/reference/other-new-features/indentation.html); it inserts outdent is the indent is strictly less than the previous line.

**Comment by kitbellew** [comment] 2023-02-07 15:34
> > that's not what the rule says (https://docs.scala-lang.org/scala3/reference/other-new-features/indentation.html); it inserts outdent is the indent is strictly less than the previous line.
> 
> The rules define `<indent>` and `<outdent>` tokens in 2.1 and 2.2, but then say (the text after 2.2.2):
> 
> > It is an error if the indentation width of the token following an <outdent> does not match the indentation of some previous line in the enclosing indentation region.
> 
> So what happens is that in your example code the `.toString` does produces an `<outdent>` (because it has less indentation than the current block), but the `<outdent>` is then rejected because it does not align with any of the prior blocks.

.toString doesn't start an optional-braces region and hence can hardly refer to any of them.

if the compiler cannot parse the less-indented .toString, then the problem could be in the compiler, or [SIP-44](https://docs.scala-lang.org/sips/fewer-braces.html) implementation, or the SIP is a bit incomplete.

**Comment by kitbellew** [comment] 2023-02-07 16:16
> > .toString doesn't start an optional-braces region and hence can hardly refer to any of them.
> 
> This is not about `.toString` specifically, but about any line with less indentation than the current indented block has. As in, the `.toString` introduces an `<outdent>` due to rule 2.2.1:
> 
> > 2.2.1) the first token on the next line has an indentation width strictly less than the current indentation width
> 
> To me, it seems the intent of the rules is precisely to prevent any “in between” indentation, because it would be unclear which block is closed.

It's possible since in all other prior optional-braces cases the next line starts a separate expression (there are explicit exclusions for `else` etc.).

however, fewer-braces explicitly introduces a new case which can in fact have continuations and hence should not work the same way (and fewer-braces already behaves differently since it allows `map: x =><indent>` unlike the usual rule which rules indent to be right after colon). that's what i meant about SIP-44 being incomplete.

**Comment by kitbellew** [comment] 2023-02-07 16:43
so, what do we do? 😃

**Comment by tgodzik** [comment] 2023-02-07 18:19
> so, what do we do? smiley

I think we have two options:
- make the fewer indentation larger than normal one
- behave inconsistent if we don't have a closing }

I would opt for the second option since in reality we can behave inconsistent here, it's a totally new way of writting code, so no old users will be surprised.

**Comment by kitbellew** [comment] 2023-02-09 23:03
> > so, what do we do? smiley
> 
> I think we have two options:
> 
> * make the fewer indentation larger than normal one
> * behave inconsistent if we don't have a closing }
> 
> I would opt for the second option since in reality we can behave inconsistent here, it's a totally new way of writting code, so no old users will be surprised.

I have implemented option 1. the issue was that apply-after-select
```
foo.bar:
    body
  .baz
```
was already formatted correctly, and only apply-without-select
```
foo:
    body
  .baz
```
wasn't.

so rather than changing the indentation rules for existing cases, just fixed the remaining one.

**Closed** 2023-02-10 20:06 UTC

**Comment by soronpo** [comment] 2023-03-05 11:45
I'm sorry I didn't know about this thready earlier, but Option 1 is no good for me. It makes the code look inconsistent. 
It's as if we had a separate `indent.fewerBracesSite` option, that I could not find how to configure.

**Comment by soronpo** [comment] 2023-03-05 12:12
I opened the issue https://github.com/scalameta/scalafmt/issues/3489
