### ISSUE TITLE
coursier trying to download poms every single time

### ISSUE THREAD

**Issue by fommil** [scalameta/scalafmt#925] opened 2017-05-08 14:58 UTC
to workaround #923 I'm doing this

```scala
package org.scalafmt.sbt

import sbt._
import sbt.Keys._

// WORKAROUND https://github.com/scalameta/scalafmt/issues/923
object ScalafmtPlugin extends AutoPlugin {
  override def trigger: PluginTrigger = allRequirements

  val latestScalafmt = "0.7.0-RC1"

  object autoImport {
    val scalafmt: Command =
      Command.args("scalafmt", "Run scalafmt cli.") {
        case (state, args) =>
          val Right(scalafmt) =
            org.scalafmt.bootstrap.ScalafmtBootstrap.fromVersion(latestScalafmt)
          scalafmt.main("--non-interactive" +: args.toArray)
          state
      }
  }

  override def globalSettings: Seq[Def.Setting[_]] = Seq(
    commands += autoImport.scalafmt
  ) ++ addCommandAlias("scalafmtTest", "scalafmt --test") ++
    addCommandAlias("scalafmtDiffTest", "scalafmt --diff --test") ++
    addCommandAlias("scalafmtDiff", "scalafmt --diff")

}
```

but when I run any `scalafmt` there is I/O taking place with this output, which is incredibly inefficient

```
[error] Downloading https://dl.bintray.com/scalameta/maven/com/geirsson/scalafmt-cli_2.11/0.7.0-RC1/scalafmt-cli_2.11-0.7.0-RC1.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/geirsson/scalafmt-cli_2.11/0.7.0-RC1/scalafmt-cli_2.11-0.7.0-RC1.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/scalameta_2.11/1.7.0/scalameta_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/geirsson/scalafmt-core_2.11/0.7.0-RC1/scalafmt-core_2.11-0.7.0-RC1.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/martiansoftware/nailgun-server/0.9.1/nailgun-server-0.9.1.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/github/scopt/scopt_2.11/3.5.0/scopt_2.11-3.5.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/scalameta_2.11/1.7.0/scalameta_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/martiansoftware/nailgun-server/0.9.1/nailgun-server-0.9.1.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/geirsson/scalafmt-core_2.11/0.7.0-RC1/scalafmt-core_2.11-0.7.0-RC1.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/github/scopt/scopt_2.11/3.5.0/scopt_2.11-3.5.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scala-lang/scala-library/2.11.11/scala-library-2.11.11.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scala-lang/scala-library/2.11.11/scala-library-2.11.11.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/sonatype/oss/oss-parent/7/oss-parent-7.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/geirsson/metaconfig-typesafe-config_2.11/0.3.2/metaconfig-typesafe-config_2.11-0.3.2.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/geirsson/metaconfig-typesafe-config_2.11/0.3.2/metaconfig-typesafe-config_2.11-0.3.2.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/common_2.11/1.7.0/common_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/common_2.11/1.7.0/common_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/semantic_2.11/1.7.0/semantic_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/semantic_2.11/1.7.0/semantic_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/transversers_2.11/1.7.0/transversers_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/geirsson/metaconfig-core_2.11/0.3.2/metaconfig-core_2.11-0.3.2.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/transversers_2.11/1.7.0/transversers_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/geirsson/metaconfig-core_2.11/0.3.2/metaconfig-core_2.11-0.3.2.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/inline_2.11/1.7.0/inline_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/parsers_2.11/1.7.0/parsers_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/inline_2.11/1.7.0/inline_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/parsers_2.11/1.7.0/parsers_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/quasiquotes_2.11/1.7.0/quasiquotes_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/quasiquotes_2.11/1.7.0/quasiquotes_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/dialects_2.11/1.7.0/dialects_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/tokenizers_2.11/1.7.0/tokenizers_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/tokenizers_2.11/1.7.0/tokenizers_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/dialects_2.11/1.7.0/dialects_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/trees_2.11/1.7.0/trees_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/trees_2.11/1.7.0/trees_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/trueaccord/scalapb/scalapb-runtime_2.11/0.6.0-pre2/scalapb-runtime_2.11-0.6.0-pre2.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/typesafe/config/1.2.1/config-1.2.1.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/typesafe/config/1.2.1/config-1.2.1.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/lihaoyi/sourcecode_2.11/0.1.3/sourcecode_2.11-0.1.3.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/trueaccord/scalapb/scalapb-runtime_2.11/0.6.0-pre2/scalapb-runtime_2.11-0.6.0-pre2.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/lihaoyi/sourcecode_2.11/0.1.3/sourcecode_2.11-0.1.3.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/tokens_2.11/1.7.0/tokens_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/inputs_2.11/1.7.0/inputs_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/lihaoyi/scalaparse_2.11/0.4.2/scalaparse_2.11-0.4.2.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/tokens_2.11/1.7.0/tokens_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/lihaoyi/scalaparse_2.11/0.4.2/scalaparse_2.11-0.4.2.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/inputs_2.11/1.7.0/inputs_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/lihaoyi/fastparse_2.11/0.4.2/fastparse_2.11-0.4.2.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/google/protobuf/protobuf-java/3.2.0/protobuf-java-3.2.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/lihaoyi/fastparse_2.11/0.4.2/fastparse_2.11-0.4.2.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/google/protobuf/protobuf-java/3.2.0/protobuf-java-3.2.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/io_2.11/1.7.0/io_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/io_2.11/1.7.0/io_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/trueaccord/lenses/lenses_2.11/0.4.10/lenses_2.11-0.4.10.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/trueaccord/lenses/lenses_2.11/0.4.10/lenses_2.11-0.4.10.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/google/protobuf/protobuf-parent/3.2.0/protobuf-parent-3.2.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/google/protobuf/protobuf-parent/3.2.0/protobuf-parent-3.2.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/google/google/1/google-1.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/google/google/1/google-1.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/lihaoyi/fastparse-utils_2.11/0.4.2/fastparse-utils_2.11-0.4.2.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/lihaoyi/fastparse-utils_2.11/0.4.2/fastparse-utils_2.11-0.4.2.pom.sha1
```

**Comment by fommil** [comment] 2017-05-08 15:03
workaround seems to be to use v0.6.6 of the bootstrapper. must be a 0.6.7 or 0.6.7 regression.

**Comment by olafurpg** [comment] 2017-05-08 16:37
Duplicate of https://github.com/scalameta/scalafmt/issues/879 I have now updated the docs in http://scalameta.org/scalafmt/#sbt0.13 to use 0.6.6 instead of 0.6.8

I suspect the regression was related to adding a new resolver to support using pre-release versions from the bintray:scalameta/maven repository.

**Closed by olafurpg** 2017-05-08 16:37 UTC
