### ISSUE TITLE
Exception in scalafmt

### ISSUE THREAD

**Issue by Arthurm1** [scalameta/scalafmt#3810] opened 2024-03-04 11:50 UTC
## Configuration (required) ##

```
version = "3.8.0"
runner.dialect = scala3
maxColumn = 120
align.preset = some
align.stripMargin = true
docstrings.style = Asterisk
docstrings.wrap = no
assumeStandardLibraryStripMargin = true
newlines.inInterpolation = avoid
lineEndings = preserve
```

## Command-line parameters (required) ##

Tried with `scalafmt Foo.scala` but used Gradle plugin to get stacktrace.  Error happens with both

## Steps

Given code like this:
```scala
class Foo {
  def foo(value: Int): String => Boolean = value match {
    case _ =>
      val res = false
      (str: String) => res
  }
}
```

## Problem

Scalafmt formats code like this:
```scala

error: src\main\scala\Foo.scala: org.scalafmt.dynamic.exceptions.PositionExceptionImpl: src\main\scala\Foo.scala:5: error: [dialect scala3] ; expected but => found
      (str: String) => res
                    ^
Caused by: src\main\scala\Foo.scala:5: error: [dialect scala3] ; expected but => found
      (str: String) => res
                    ^
        at org.scalafmt.Scalafmt$.$anonfun$doFormatOne$2(Scalafmt.scala:147)
        at scala.meta.parsers.Parsed.fold(Errors.scala:12)
        at scala.meta.parsers.Parsed.fold$(Errors.scala:10)
        at scala.meta.parsers.Parsed$Error.fold(Errors.scala:28)
        at org.scalafmt.Scalafmt$.doFormatOne(Scalafmt.scala:150)
        at org.scalafmt.Scalafmt$.doFormat(Scalafmt.scala:124)
        at org.scalafmt.Scalafmt$.formatCodeWithStyle(Scalafmt.scala:104)
        at org.scalafmt.Scalafmt$.$anonfun$formatCode$3(Scalafmt.scala:77)
        at scala.util.Success.fold(Try.scala:281)
        at org.scalafmt.Scalafmt$.formatCode(Scalafmt.scala:77)
        at org.scalafmt.Scalafmt$.format(Scalafmt.scala:58)
        at org.scalafmt.Scalafmt.format(Scalafmt.scala)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.scalafmt.dynamic.ScalafmtReflect.format(ScalafmtReflect.scala:107)
        at org.scalafmt.dynamic.ScalafmtReflectConfig.format(ScalafmtReflectConfig.scala:121)
        at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$tryFormat$1(ScalafmtDynamic.scala:203)
        at scala.util.Try$.apply(Try.scala:213)
        at org.scalafmt.dynamic.ScalafmtDynamic.org$scalafmt$dynamic$ScalafmtDynamic$$tryFormat(ScalafmtDynamic.scala:188)
        at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$formatDetailed$1(ScalafmtDynamic.scala:103)
        at scala.util.Either.flatMap(Either.scala:341)
        at org.scalafmt.dynamic.ScalafmtDynamic.formatDetailed(ScalafmtDynamic.scala:102)
        at org.scalafmt.dynamic.ScalafmtDynamic.format(ScalafmtDynamic.scala:72)
        at org.scalafmt.interfaces.Scalafmt$format$4.call(Unknown Source)
```

## Expectation

I would expect no error.

## Workaround

No workaround found.

**Comment by kitbellew** [comment] 2024-03-09 21:35
duplicate of #3790.

**Closed by kitbellew** 2024-03-09 21:35 UTC
