### ISSUE TITLE
update to latest semanticdb

### ISSUE THREAD

**Issue by fommil** [scalameta/scalafmt#1109] opened 2018-02-08 21:29 UTC
@olafurpg says that updating to a recent semanticdb is blocking scalafix from being able to use the same semanticdb jar, managed by sbt.

I couldn't find an existing ticket for the upgrade, so creating this.

Apparently this is not easy.

**Comment by olafurpg** [comment] 2018-02-08 21:36
Duplicate of #975 

Scalameta v2.0 did several breaking changes on the Tree API that scalafmt uses heavily. Scalafmt does not use semanticdb.

Note, I haven't even gotten around to upgrade to 1.8 from 1.7, when I tried I had some failing tests I didn't dig into.

**Closed by olafurpg** 2018-02-08 21:36 UTC
