### ISSUE TITLE
Parsing error "illegal start of simple expression"

### ISSUE THREAD

**Issue by ochrons** [scalameta/scalafmt#978] opened 2017-06-17 18:11 UTC
This template is a guideline, not a strict requirement.
- **Version**: 1.0.0-RC3 (and 0,6,8)
- **Integration**: IntelliJ
- **Configuration**:
```
style = defaultWithAlign
maxColumn = 125
```

## Steps

use scalafmt on file:

https://github.com/suzaku-io/suzaku/blob/4b1e3af49da681d039d42f7673a2e4424765c2e8/webdemo/src/main/scala/webdemo/WebDemoApp.scala#L36

## Problem

```scala
WebDemoApp.scala: <input>:36: error: illegal start of simple expression
) << GreenButton,
        ^
```

The file compiles just fine.

**Comment by olafurpg** [comment] 2017-06-17 18:25
There's a trailing comma in the line above https://github.com/suzaku-io/suzaku/blob/4b1e3af49da681d039d42f7673a2e4424765c2e8/webdemo/src/main/scala/webdemo/WebDemoApp.scala#L35

The scalameta parser supports trailing commas under a 212 dialect, but changing the dialect was more problematic than I thought i'd be, see https://github.com/scalameta/scalafmt/issues/909 and https://github.com/scalameta/scalafmt/issues/830

**Comment by olafurpg** [comment] 2017-06-17 18:38
It seems I will be able to fix #830 after all. Support for trailing commas and other new syntax like literal types will be included in 1.0.0. Closing as duplicate of #909

**Closed by olafurpg** 2017-06-17 18:38 UTC

**Comment by ochrons** [comment] 2017-06-17 19:11
Oh, didn't even notice the trailing comma :)

**Comment by cb372** [comment] 2017-09-13 16:32
Same here, I just ran into this bug and didn't notice that I was accidentally using Scala's new trailing comma support for the first time 😁

**Comment by Infinite-Progresss** [comment] 2023-03-23 08:04
get it
