### ISSUE TITLE
Scalafmt 3.8.0 update: suspicous reformatting

### ISSUE THREAD

**Issue by adamw** [scalameta/scalafmt#3799] opened 2024-02-26 11:58 UTC
In an automated 3.8.0 update, which broke the build, I noticed some suspicious reformatting: 

From:

```scala
data.workers.get(host) match {
           case None =>
             val workerQueue = new ArrayBlockingQueue[Url](32)
             worker(workerQueue, crawlerQueue)
             (data.copy(workers = data.workers + (host -> workerQueue)), workerQueue)
           case Some(queue) => (data, queue)
         }
```

to:
```
data.workers.get(host) match {
           case None =>
             val workerQueue = new ArrayBlockingQueue[Url](32)
             worker(workerQueue, crawlerQueue)(data.copy(workers = data.workers + (host -> workerQueue)), workerQueue)
           case Some(queue) => (data, queue)
         }
```

The intent was to first call `worker(workerQueue, crawlerQueue)`, and then return a tuple. So the reformatting seems wrong.

See [the full PR](https://github.com/softwaremill/ox/pull/77/files)

**Comment by adamw** [comment] 2024-02-26 12:02
Similar problems [in tapir](https://github.com/softwaremill/tapir/pull/3524/files) and [in sttp](https://github.com/softwaremill/sttp/pull/2081/files)

**Comment by kitbellew** [comment] 2024-02-26 12:02
duplicate of #3789 and #3790.

**Closed as completed by kitbellew** 2024-02-26 12:02 UTC

**Comment by adamw** [comment] 2024-02-26 12:05
Oh sorry, I didn't see anything in open issues and create a new one. Thanks, waiting for a release then :)
