### ISSUE TITLE
trailing newlines, comments and dangling parens

### ISSUE THREAD

**Issue by fommil** [scalameta/scalafmt#1128] opened 2018-04-04 15:11 UTC
```scala
case class Foo (
  a: String,
 // b: String
)
```

is reformatted to

```scala
 case class Foo (
  a: String,
 // b: String)
```

which captures valid code in a comment (final `)`)

I'm using

```
danglingParentheses = true
```

**Comment by olafurpg** [comment] 2018-04-04 15:19
Is that all the configuration? I am unable to reproduce with 1.4.0

**Comment by olafurpg** [comment] 2018-04-04 15:28
I'm able to reproduce with those settings, thanks!

**Comment by olafurpg** [comment] 2018-04-04 15:30
The culprit is `verticalMultilineAtDefinitionSite = true`, @pjrt could you take a look?

**Comment by pjrt** [comment] 2018-04-04 15:43
Yep, dupe of https://github.com/scalameta/scalafmt/issues/966

I have been lazy with that issue since no one else had complained yet, but I guess it is time

**Comment by pjrt** [comment] 2018-04-04 15:44
Opps, wrong button.

But actually, this should be closed, right? Idk what the procedure in this repo is for dupes @olafurpg

**Closed** 2018-04-04 15:45 UTC
