### ISSUE TITLE
Incorrect inline macro indentation

### ISSUE THREAD

**Issue by timothyklim** [scalameta/scalafmt#2478] opened 2021-04-29 13:20 UTC
- **Version**: 3.0.0-RC2
- **Integration**: CLI
- **Configuration**:
```
version = 3.0.0-RC2
maxColumn = 150
assumeStandardLibraryStripMargin = true
continuationIndent.callSite = 2
includeCurlyBraceInSelectChains = true
binPack.literalArgumentLists = false
rewrite.rules = [AvoidInfix, SortImports, SortModifiers, RedundantParens, PreferCurlyFors]

runner.dialect = scala3
rewrite.scala3 {
  convertToNewSyntax = true
  removeOptionalBraces = true
}

newlines {
  alwaysBeforeCurlyBraceLambdaParams = false
  implicitParamListModifierPrefer = before
}

align = none
align {
  preset = none
  stripMargin = true
  openParenCallSite = false
  openParenDefnSite = false
  tokens = [
    "%", "%%", "%%%", ":=", "~=", "=>"
  ]
}
```

## Steps

Given code like this:
```scala
inline def encodeFlat[T <: Enum | Singleton](inline buf: ByteStringBuilder, xs: collection.Seq[T]): ByteStringBuilder =
    buf.putInt(xs.size)
    inline erasedValue[T] match
      case _: Enum      => xs.foreach(_.encodeFull(buf))
      case _: Singleton => xs.foreach(_.encodeBody(buf))
    buf
```

When I run scalafmt like this:

```bash
scalafmt -c .scalafmt3.conf --non-interactive
```

## Problem

Scalafmt formats code like this:
```scala
inline def encodeFlat[T <: Enum | Singleton](inline buf: ByteStringBuilder, xs: collection.Seq[T]): ByteStringBuilder =
    buf.putInt(xs.size)
    inline
    erasedValue[T] match
      case _: Enum      => xs.foreach(_.encodeFull(buf))
      case _: Singleton => xs.foreach(_.encodeBody(buf))
    buf
```

## Expectation

I would like the formatted output to look like this:
```scala
inline def encodeFlat[T <: Enum | Singleton](inline buf: ByteStringBuilder, xs: collection.Seq[T]): ByteStringBuilder =
    buf.putInt(xs.size)
    inline erasedValue[T] match
      case _: Enum      => xs.foreach(_.encodeFull(buf))
      case _: Singleton => xs.foreach(_.encodeBody(buf))
    buf
```

**Comment by tgodzik** [comment] 2021-04-29 15:56
Thanks for reporting, part of the issue is in https://github.com/scalameta/scalameta/pull/2320 but I think we will also need to fix it in Scalafmt.

**Comment by note** [comment] 2021-04-30 06:07
I was about to create an issue about nested inline matches when I realized what I stumbled upon is probably just another instance of that issue.

Pasting it here anyway, just so you have more test cases:

Given Scala 3 code like this:

```scala
inline def repro[T <: Int with Singleton, U <: Int with Singleton]: Int = 
  inline erasedValue[T] match
    case _: 5 => 5
    case _: 6 =>
      inline erasedValue[T] < erasedValue[U] match
        case _: true => 100
        case _: false => 101
    case _    => 0
```

Scalafmt formats code like this:

```scala
inline def repro[T <: Int with Singleton, U <: Int with Singleton]: Int =
  inline erasedValue[T] match
    case _: 5 => 5
    case _: 6 =>
        inline
      erasedValue[T] < erasedValue[U] match
        case _: true  => 100
        case _: false => 101
    case _ => 0
```

Which makes the code not compile.

**Comment by kitbellew** [comment] 2021-05-13 16:12
@tgodzik should we close this?

**Comment by tgodzik** [comment] 2021-05-13 16:18
Added a test here https://github.com/scalameta/scalafmt/pull/2508

**Closed** 2021-05-13 16:29 UTC
Labels: bug in dependency
