### ISSUE TITLE
Curried methods over line width are not formatted nicely

### ISSUE THREAD

**Issue by jvilarsan** [scalameta/scalafmt#849] opened 2017-03-22 11:44 UTC
This template is a guideline, not a strict requirement.
- **Version**: 0.6.4
- **Integration**: IntelliJ
- **Configuration**:
```
style = defaultWithAlign
maxColumn = 120
align.arrowEnumeratorGenerator = true
project.includeFilters = [".*\\.scala"]
importSelectors = singleLine
```

## Steps

I ran scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
 def findAllVersions(callback: TimingCallback = NoOpTimingCallback)(
      seqs: Seq[Car]): Future[Seq[ContentCarSeqAndVersion]]
```

## Expectation

I would like the formatted output to look like this:
```scala
 def findAllVersions(callback: TimingCallback = NoOpTimingCallback)
                    (seqs: Seq[Car]): Future[Seq[ContentCarSeqAndVersion]]
```

## Workaround

None  😭 

## Notes

See also..

**Comment by olafurpg** [comment] 2017-04-29 19:48
Thank you for reporting. Closing as duplicate of https://github.com/scalameta/scalafmt/issues/337 

One possible workaround, although not expected output

```
verticalMultilineAtDefinitionSite = true
```

**Closed by olafurpg** 2017-04-29 19:48 UTC
