### ISSUE TITLE
Non-idempotent behaviour of named argument alignment

### ISSUE THREAD

**Issue by adamwy** [scalameta/scalafmt#914] opened 2017-04-27 16:48 UTC
- **Version**: 0.6.7
- **Integration**: IntelliJ
- **Configuration**:
```
style = defaultWithAlign
maxColumn = 100

align.tokens.add = [
  { code = "=",   owner = "Term.Arg.Named"  }
]

```

## Problem

Scalafmt seems to randomly align either methods or named arguments (never both):

```scala
object Test {
  def foo(x: Int, yy: Int) = ???

  def abc  = ???
  def abcd = ???

  val y =
    foo(
      x = 3,
      yy = 5
    )
}
```

```scala
object Test {
  def foo(x: Int, yy: Int) = ???

  def abc = ???
  def abcd = ???

  val y =
    foo(
      x  = 3,
      yy = 5
    )
}
```

## Expectation

I would like the formatted output to look like this:
```scala
object Test {
  def foo(x: Int, yy: Int) = ???

  def abc  = ???
  def abcd = ???

  val y =
    foo(
      x  = 3,
      yy = 5
    )
}
```

**Comment by olafurpg** [comment] 2017-04-29 18:52
Thank you for reporting! Term.Arg.Named is disabled by default because it has several issues, including this one (which I've known about for a while).

I can't promise this will get fixed. For now, I recommend disabling custom vertical alignment for Term.Arg.Named.

**Comment by olafurpg** [comment] 2017-04-29 18:53
If you are interested in taking a swing at this, I'm happy to give pointers. I suspect it may be related to this (evil) global cache here https://github.com/scalameta/scalameta/blob/fac0de590bf0633567a12ce38de2cf40c5b1b547/scalameta/tokenizers/jvm/src/main/scala/scala/meta/internal/tokenizers/PlatformTokenizerCache.scala#L15 but I haven't been able to validate if that's the case.

**Comment by olafurpg** [comment] 2017-04-29 19:12
Closing this as duplicate of https://github.com/scalameta/scalafmt/issues/850

**Closed by olafurpg** 2017-04-29 19:12 UTC
Labels: bug
