### ISSUE TITLE
Newline import after package name 

### ISSUE THREAD

**Issue by allantl** [scalameta/scalafmt#1259] opened 2018-08-18 17:24 UTC
Is there a rule that formats

```
package x.y.z
import scala.concurrent.Future
import scala.util.Try

```

into 
```
package x.y.z

import scala.concurrent.Future
import scala.util.Try

```

I couldn't find a rule to do this in the documentation (Sorry, if this is already supported)

**Comment by olafurpg** [comment] 2018-08-20 06:34
Thanks for reported! This is a duplicate of https://github.com/scalameta/scalafmt/issues/1069, I agree this would be a nice feature

**Closed by olafurpg** 2018-08-20 06:34 UTC
