### ISSUE TITLE
Keep scalameta and  scalafmt latest versions in sync

### ISSUE THREAD

**Issue by MasseGuillaume** [scalameta/scalafmt#1035] opened 2017-08-31 10:12 UTC
In [Scastie](https://github.com/scalacenter/scastie), we use both scalameta and scalafmt. Scalameta for the instrumentation and scalafmt for formatting.

The latest scalafmt (1.2.0) is using scalameta 1.7.0. It would be nice if scalafmt is more in sync with scalameta. I know this means development time, I would be happy to make this happen.

Cheers!

**Comment by olafurpg** [comment] 2017-08-31 11:25
I agree it would be super to upgrade to the latest scalameta, lack of time is the biggest issuse. The scalafmt codebase is very tightly coupled with scalameta ASTs so I estimate accommodating the changes in 2.0.0 may take up to a full-day.

**Comment by olafurpg** [comment] 2017-09-21 10:15
Duplicate of #975

**Closed by olafurpg** 2017-09-21 10:15 UTC
