### ISSUE TITLE
Not parsing single line methods correctly when the single line is on different lines

### ISSUE THREAD

**Issue by spf3000** [scalameta/scalafmt#1265] opened 2018-08-30 14:48 UTC
This template is a guideline, not a strict requirement.
- **Version**: 1.5.1
- **Integration**: Neovim (but I verified the same behaviour with sbt plugin and `sbt scalafmt`
- **Configuration**:
align = more    # For pretty alignment.
maxColumn = 120 # For my wide 30" display.

## Steps

Given code like this:
```
  private def extractTextRequest(gold: GoldenXml, textAnnotations: Seq[XmlTextAnnotation]) =
    Request[IO](Method.POST, Uri.uri("/combine-text"))
      .withBody(GoldenWithTextAnnotations(gold.text, textAnnotations).asJson)
      .unsafeRunSync()

  private def extractBratTextRequest(gold: GoldenXml, textAnnotations: Seq[XmlTextAnnotation]) =
    Request[IO](Method.POST, Uri.uri("/combine-brat-text"))
      .withBody(GoldenWithTextAnnotations(gold.text, textAnnotations).asJson)
      .unsafeRunSync()
```

When I run scalafmt like this:

```fish
sbt scalafmt
```

## Problem
Scalafmt is formatting subsequent methods as if they are lines in the previous method when there are no brackets closing the method and they are more than one line of code
Scalafmt formats code like this:
```
  private def extractTextRequest(gold: GoldenXml, textAnnotations: Seq[XmlTextAnnotation]) =
    Request[IO](Method.POST, Uri.uri("/combine-text"))
      .withBody(GoldenWithTextAnnotations(gold.text, textAnnotations).asJson)
      .unsafeRunSync()

      private def extractBratTextRequest(gold: GoldenXml, textAnnotations: Seq[XmlTextAnnotation]) =
        Request[IO](Method.POST, Uri.uri("/combine-brat-text"))
          .withBody(GoldenWithTextAnnotations(gold.text, textAnnotations).asJson)
          .unsafeRunSync()
```

## Expectation

I would like the formatted output to look like this:
```scala
  private def extractTextRequest(gold: GoldenXml, textAnnotations: Seq[XmlTextAnnotation]) =
    Request[IO](Method.POST, Uri.uri("/combine-text"))
      .withBody(GoldenWithTextAnnotations(gold.text, textAnnotations).asJson)
      .unsafeRunSync()

  private def extractBratTextRequest(gold: GoldenXml, textAnnotations: Seq[XmlTextAnnotation]) =
    Request[IO](Method.POST, Uri.uri("/combine-brat-text"))
      .withBody(GoldenWithTextAnnotations(gold.text, textAnnotations).asJson)
      .unsafeRunSync()
```

**Comment by ShaneDelmore** [comment] 2018-09-10 18:50
Does it happen if you format twice?  I'm not sure if it's related but I am currently trying to minimize some idempotency issues that look similar, the first time I format I get an extra level of indentation, the second time it goes away and then the formatting stabilizes.

**Comment by spf3000** [comment] 2018-09-13 13:46
@ShaneDelmore Actually no, when I repeat the format command it goes away. If you're already working on it I will close the issue? :)

**Comment by olafurpg** [comment] 2018-09-13 13:50
Thanks for reporting @spf3000 I am unable to reproduce, can you please include more context?
```
cat .scalafmt.conf
align = more # For pretty alignment.
maxColumn = 120 # For my wide 30" display.
➜  target git:(master) ✗ cat foo.scala
object a {
    private def extractTextRequest(gold: GoldenXml, textAnnotations: Seq[XmlTextAnnotation]) =
    Request[IO](Method.POST, Uri.uri("/combine-text"))
      .withBody(GoldenWithTextAnnotations(gold.text, textAnnotations).asJson)
      .unsafeRunSync()

  private def extractBratTextRequest(gold: GoldenXml, textAnnotations: Seq[XmlTextAnnotation]) =
    Request[IO](Method.POST, Uri.uri("/combine-brat-text"))
      .withBody(GoldenWithTextAnnotations(gold.text, textAnnotations).asJson)
      .unsafeRunSync()
}
➜  target git:(master) ✗ coursier launch com.geirsson:scalafmt-cli_2.12:1.5.1  -- --stdout foo.scala
object a {
  private def extractTextRequest(gold: GoldenXml, textAnnotations: Seq[XmlTextAnnotation]) =
    Request[IO](Method.POST, Uri.uri("/combine-text"))
      .withBody(GoldenWithTextAnnotations(gold.text, textAnnotations).asJson)
      .unsafeRunSync()

  private def extractBratTextRequest(gold: GoldenXml, textAnnotations: Seq[XmlTextAnnotation]) =
    Request[IO](Method.POST, Uri.uri("/combine-brat-text"))
      .withBody(GoldenWithTextAnnotations(gold.text, textAnnotations).asJson)
      .unsafeRunSync()
}
```

**Comment by ShaneDelmore** [comment] 2018-09-14 04:27
> @ShaneDelmore Actually no, when I repeat the format command it goes away. If you're already working on it I will close the issue? :)

I am not working on it and don't anticipate having time to work on this anytime soon. I did create a pr with some tests demonstrating similar idempotency issues, but I don't think anyone has time budgeted to tackle them in the near term.  I have an open PR showing how to reproduce various issues I found, you might want to take a look and see if you can come up with a minimal test demonstrating the issue you are reporting here since it isn't easily reproduced.

**Comment by poslegm** [comment] 2019-11-08 17:08
I can't reproduce it too

**Comment by kitbellew** [comment] 2020-05-11 16:51
i will close it as it's not reproducible in recent versions.

**Closed by kitbellew** 2020-05-11 16:51 UTC
Labels: need more info
