### ISSUE TITLE
Wrong formatting of code blocks with partial functions returning tuples

### ISSUE THREAD

**Issue by pawelsadlo** [scalameta/scalafmt#3844] opened 2024-03-22 21:30 UTC
Please paste the contents of your `.scalafmt.conf` file here:
```
version = 3.8.0
runner.dialect = scala3
```

When I run scalafmt via CLI like this: `scalafmt File.scala`

## Steps

Given code like this:
```scala
class Sfmt {
  val pr: PartialFunction[Int, (String, Int)] = {
    case e: Int =>
      val a = ""
      ("first", 2)
  }

  try {
    ()
  } catch {
    case e: Throwable =>
      println("")
      (1, false)
  }


  1 match {
    case 2 =>
      println("")
      (1, false)
  }
  
  List.empty[Matchable].collect{
    case x:Int =>
      val a = 1
      (a)
  }
}
```

## Problem

Scalafmt formats code like this:
```scala
class Sfmt {
  val pr: PartialFunction[Int, (String, Int)] = { case e: Int =>
    val a = "" ("first", 2)
  }

  try {
    ()
  } catch {
    case e: Throwable =>
      println("")(1, false)
  }

  1 match {
    case 2 =>
      println("")(1, false)
  }

  List.empty[Matchable].collect { case x: Int =>
    val a = 1 (a)
  }
}
```

## Expectation

I would like the formatted output to look like this:
```scala
class Sfmt {
  val pr: PartialFunction[Int, (String, Int)] = { case e: Int =>
    val a = ""
    ("first", 2)
  }

  try {
    ()
  } catch {
    case e: Throwable =>
      println("")
      (1, false)
  }

  1 match {
    case 2 =>
      println("")
      (1, false)
  }

  List.empty[Matchable].collect { case x: Int =>
    val a = 1
    (a)
  }
}
```

## Notes
I gave several examples where the bug occurs.

The pattern is that we have code block with `case` starting from new line, followed by any line (or lines), followed by line containing code in parenthesis (for example tuples).

**Comment by joan38** [comment] 2024-03-26 22:37
Same here since 3.8.0 ✋🏼 

.scalafmt.conf
```
version = 3.8.0
runner.dialect = scala3
maxColumn = 120
```

FmtTest.scala
```scala
val (sessionOffsetBasedDuration, _) = sortedTraceSequence.foldLeft((0L, 0L)) {
  case ((currentSoffBasedDuration, lastSoff), eventToProcess) =>
    val updatedSoffBasedDuration =
      if true
      then currentSoffBased + (eventToProcess.session_offset_ms - lastSoff)
      else currentSoffBased
    (updatedSoffBasedDuration, eventToProcess)
}
```

```
scala-cli fmt FmtTest.scala
```

Yields the wrong code:
```scala
val (sessionOffsetBasedDuration, _) = sortedTraceSequence.foldLeft((0L, 0L)) {
  case ((currentSoffBasedDuration, lastSoff), eventToProcess) =>
    val updatedSoffBasedDuration =
      if true
      then currentSoffBased + (eventToProcess.session_offset_ms - lastSoff)
      else currentSoffBased(updatedSoffBasedDuration, eventToProcess)
}
```

**Comment by kitbellew** [comment] 2024-03-27 18:55
this is yet another duplicate of #3790 (and of #3811 and #3824) but this time i will keep it open until the next release, so that people don't create more :)

**Closed** 2024-03-29 07:29 UTC
