### ISSUE TITLE
Add support to .editorconfig

### ISSUE THREAD

**Issue by ljmf00** [scalameta/scalafmt#1458] opened 2019-07-20 13:33 UTC
# Feature request

Because EditorConfig is a "standard" on a lot of text editors, should be cool to add `.editorconfig` as a fallback config file.

There are two possible features to take here:

1. Add support for `.editorconfig` entries, in case scalafmt config is missing.
2. Use `.editorconfig` custom entries to describe custom features implemented by scalafmt.

## What is EditorConfig?

EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.

Check out the editors that already have native support to it and some already implemented custom fmt using `.editorconfig` for D.

---
Reference:
- https://editorconfig.org/
- https://github.com/dlang-community/dfmt

**Comment by tanishiking** [comment] 2019-07-20 16:11
It looks nice to support the `.editorconfigrc`!
What we have to do for supporting EditorConfig is

- find `.editorconfigrc` (from all the scalafmt plugin)
- convert it into a corresponding configuration for scalafmt
- format using scalafmt

**Comment by ljmf00** [comment] 2019-07-20 17:43
@tanishiking not `.editorconfigrc`, its `.editorconfig` instead.

**Comment by NiccoMlt** [comment] 2021-01-08 16:08
Supporting EditorConfig would be great!

Are there any news regarding its support?

**Comment by kitbellew** [comment] 2021-09-11 14:31
what's the benefit of using one for scalafmt? the idea is to use one file to configure any editor but scalafmt is not an editor. the configuration described had no options supported by scalafmt (only indent was added last month to the formatter), and the result of scalafmt formatting will be incompatible with all combinations but one.

please add an explicit mapping of editorconfig options to scalafmt configuration, or close this feature request.

**Comment by ljmf00** [comment] 2021-09-12 16:25
> what's the benefit of using one for scalafmt? the idea is to use one file to configure any editor but scalafmt is not an editor.

That's not the point. Editorconfig is not to configure/personalize your editor and rather make a configuration to tell the editor to conform with the project code style and formatting guidelines.

> the configuration described had no options supported by scalafmt (only indent was added last month to the formatter), and the result of scalafmt formatting will be incompatible with all combinations but one.

I guess you either misunderstood my point or didn't read the description fully, because there are two possible features to take here:

1. Add support for `.editorconfig` entries, in case scalafmt config is missing.
2. Use `.editorconfig` custom entries to describe custom features implemented by scalafmt.

As I mentioned in the issue description, you can take a look at the D formatting tool. I'm going to add those points into the issue description for completeness.

> please add an explicit mapping of editorconfig options to scalafmt configuration, or close this feature request.

The point would be to support a standardized configuration in case scalafmt configuration is not present or if the project choose to map scalafmt options directly to `.editorconfig`. This is possible because `editorconfig` is designed to ignore config keys that the editor/tool doesn't recognize, according to its specification:

	EditorConfig plugins shall ignore unrecognized keys and invalid/unsupported values for those keys.

**Comment by kitbellew** [comment] 2021-09-12 17:36
> > what's the benefit of using one for scalafmt? the idea is to use one file to configure any editor but scalafmt is not an editor.
> 
> That's not the point. Editorconfig is not to configure/personalize your editor and rather make a configuration to tell the editor to conform with the project code style and formatting guidelines.

if the project uses scalafmt, it should use `.scalafmt`. if the editor understands scalafmt, it can read `.scalafmt`. scalafmt has 100+ parameters whereas editorconfig has less than 10.

if the project doesn't use scalafmt, and each editor needs to implement the guidelines in whatever way it wants, then you can't have options which will be supported by a subset of editors used by the users contributing to the project. no scalafmt-specific options should be added.

however, please read on as a more basic problem exists.

> I guess you either misunderstood my point or didn't read the description fully, because there are two possible features to take here:
> 
> 1. Add support for `.editorconfig` entries, in case scalafmt config is missing.
> 2. Use `.editorconfig` custom entries to describe custom features implemented by scalafmt.

most of the parameters described in https://editorconfig-specification.readthedocs.io/#supported-pairs are incompatible with scalafmt; what happens when `.editorconfig` contains `indent_style = tab` or `end_of_line = cr` or `trim_trailing_space = false` or `insert_final_newline = false`?

we can't pretend scalafmt supports `.editconfig` if it cannot produce expected output for most of the standard parameter combinations.

> As I mentioned in the issue description, you can take a look at the D formatting tool. I'm going to add those points into the issue description for completeness.

you provided a link to the repository; i don't know what you'd like me to look at. instead of guessing, i would appreciate if you shared exactly what scalafmt needs to implement.

> The point would be to support a standardized configuration in case scalafmt configuration is not present or if the project choose to map scalafmt options directly to `.editorconfig`. This is possible because `editorconfig` is designed to ignore config keys that the editor/tool doesn't recognize, according to its specification:
> 
> ```
> EditorConfig plugins shall ignore unrecognized keys and invalid/unsupported values for those keys.
> ```

however, the keys and values below are valid and supported (and scalafmt cannot handle them):
https://editorconfig-specification.readthedocs.io/#supported-pairs

let's try for one last iteration on this topic.

**Comment by ljmf00** [comment] 2021-09-12 20:00
> if the project uses scalafmt, it should use `.scalafmt`. if the editor understands scalafmt, it can read `.scalafmt`. scalafmt has 100+ parameters whereas editorconfig has less than 10.
> 
> if the project doesn't use scalafmt, and each editor needs to implement the guidelines in whatever way it wants, then you can't have options which will be supported by a subset of editors used by the users contributing to the project. no scalafmt-specific options should be added.
> 
> however, please read on as a more basic problem exists.

Just because a project uses `scalafmt`, doesn't necessarily mean that it should require a scalafmt config, ideally. The whole point of `.editorconfig` is to provide a standard way to format code style. If a project uses 30 languages, do they need to implement 30 different configs? That's the problem that `.editorconfig` is trying to solve.

> most of the parameters described in [editorconfig-specification.readthedocs.io/#supported-pairs](https://editorconfig-specification.readthedocs.io/#supported-pairs) are incompatible with scalafmt; what happens when `.editorconfig` contains `indent_style = tab` or `end_of_line = cr` or `trim_trailing_space = false` or `insert_final_newline = false`?
> 
> we can't pretend scalafmt supports `.editconfig` if it cannot produce expected output for most of the standard parameter combinations.

> you provided a link to the repository; i don't know what you'd like me to look at. instead of guessing, i would appreciate if you shared exactly what scalafmt needs to implement.

That is where D formatter tool example comes in. They implement domain-specific properties in the `.editorconfig` to support D specific features. They also ignore some `.editorconfig` properties because they don't need to support them. See https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#user-content-ideas-for-domain-specific-properties

> however, the keys and values below are valid and supported (and scalafmt cannot handle them):
> [editorconfig-specification.readthedocs.io/#supported-pairs](https://editorconfig-specification.readthedocs.io/#supported-pairs)

As I said, according to the specification, tools can ignore them safely.

**Comment by kitbellew** [comment] 2021-09-12 20:16
thanks for the explanation. at this point, I'm not clear about what needs to be implemented. feel free to reopen when you have a clear set of requirements for this feature.

**Comment by ljmf00** [comment] 2021-09-12 22:42
> thanks for the explanation. at this point, I'm not clear about what needs to be implemented. feel free to reopen when you have a clear set of requirements for this feature.

I'm sorry, I'm trying to collaborate on this, but it seems you don't, unfortunately. If you make some effort, read the example readme and the `.editorconfig` documentation, you can see the rationale here. I already tried to explain a TL;DR of what is needed. I think `.editorconfig` concept is not too hard to understand. It is a standardized config file for code style written in `ini` with key-value. Scalafmt just needs to parse it, implement their standard keys, if applicable, and add custom domain-specific keys for Scala language or Scalafmt specifically.

**Comment by kitbellew** [comment] 2021-09-12 22:52
@ljmf00 i like the idea of collaboration. since you understand what you want (and i do not), and you seem to be prepared to put in more effort, if you'd like to do yourself what you just described, we'd be happy to review your submission.

**Comment by ljmf00** [comment] 2021-09-12 23:01
> @ljmf00 i like the idea of collaboration. since you understand what you want (and i do not), and you seem to be prepared to put in more effort, if you'd like to do yourself what you just described, we'd be happy to review your submission.

I'm not usually a scala programmer. I just found this a good feature to add to scalafmt, that is why I created the issue. A lot of formatters either have support for `.editorconfig` or probably have some issue opened to implement that. See, for example, `rustfmt` [issue](https://github.com/rust-lang/rustfmt/issues/2938) for reference.

Even though I can implement this into `scalafmt`, this is not on my task list to do so and rather left this for someone interested in it. That, however, doesn't mean the issue is invalid.

**Comment by tgodzik** [comment] 2021-09-13 09:28
I agree that the issue is valid, but since the configuration for scalafmt is quite huge (take a look at https://scalameta.org/scalafmt/docs/configuration.html#other), this is quite an undertaking without clear benefits for the tool. Most projects have 2-3 languages at most so even having 3 different config files is not that huge number.

Especially that editor config supports a bit different way of configuring things and we would have to most likely update metaconfig to support that, I don't believe this is something we will tackle in the near future. Leaving it open would mean that we have plans to support it, we can reopen for sure if anyone wants to take this on.

**Comment by kitbellew** [comment] 2021-09-13 12:45
@tgodzik implementing this is impossible. the formatter cannot ever support `trim_trailing_space = false` because by design it doesn't preserve existing whitespace, whether horizontal or vertical.

**Closed** 2021-09-13 12:45 UTC
Labels: help wanted, feature request

**Comment by tgodzik** [comment] 2021-09-13 13:15
`trim_trailing_space = false` could be skipped for Scalafmt, but overall it seems like editorconfig wouldn't work here very well. Scalafmt is not an editor in essence and .editorconfig seems to have been created with those in mind.  

@ljmf00 what if this was actually handled in Metals? We could try to read the base options of editorconfig and translate that to a default scalafmt config to be used in different editors that Metals supports. Since this is an editor feature and Metals needs to work with editors, it looks like a better fit. We can move it to Metals feature-request repo to see if there is any interest.
