### ISSUE TITLE
Bloop and Scalafmt don't work together

### ISSUE THREAD

**Issue by ArulselvanMadhavan** [scalameta/scalafmt#1209] opened 2018-06-04 18:10 UTC
Hello,

I have filed two issues earlier about not being able to use `bloop` and `scalafmt` together. I was asked to wait for a new release of `scalafmt`. I tried `scalafmt-1.6.0-RC1` today. Now I am getting `NoSuchMethodError`. Can you let me know if there is a workaround for this?

1. https://github.com/scalacenter/bloop/issues/490
2. https://github.com/scalacenter/bloop/issues/453

```scala
addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.0.0-M10")
addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "1.6.0-RC1")
```
```scala
[error] java.lang.NoSuchMethodError: fastparse.all$.CharsWhileIn$default$2()I
[error] 	at scala.meta.internal.tokenizers.XmlParser.<init>(XmlParser.scala:16)
[error] 	at scala.meta.internal.tokenizers.LegacyScanner.getXml(LegacyScanner.scala:990)
[error] 	at scala.meta.internal.tokenizers.LegacyScanner.fetchLT$1(LegacyScanner.scala:347)
[error] 	at scala.meta.internal.tokenizers.LegacyScanner.fetchToken(LegacyScanner.scala:355)
[error] 	at scala.meta.internal.tokenizers.LegacyScanner.nextToken(LegacyScanner.scala:241)
[error] 	at scala.meta.internal.tokenizers.LegacyScanner.foreach(LegacyScanner.scala:1068)
[error] 	at scala.meta.internal.tokenizers.ScalametaTokenizer.uncachedTokenize(ScalametaTokenizer.scala:153)
[error] 	at scala.meta.internal.tokenizers.ScalametaTokenizer.tokenize(ScalametaTokenizer.scala:31)
[error] 	at scala.meta.internal.tokenizers.ScalametaTokenizer$$anon$2.apply(ScalametaTokenizer.scala:287)
[error] 	at scala.meta.tokenizers.Api$XtensionTokenizeDialectInput.tokenize(Api.scala:21)
[error] 	at scala.meta.tokenizers.Api$XtensionTokenizeInputLike.tokenize(Api.scala:10)
[error] 	at scala.meta.internal.parsers.ScalametaParser.scannerTokens$lzycompute(ScalametaParser.scala:183)
[error] 	at scala.meta.internal.parsers.ScalametaParser.scannerTokens(ScalametaParser.scala:183)
[error] 	at scala.meta.internal.parsers.ScalametaParser.<init>(ScalametaParser.scala:140)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anon$189.apply(ScalametaParser.scala:3462)
[error] 	at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:21)
```

**Comment by olafurpg** [comment] 2018-06-05 15:47
Thanks for reporting! This is a duplicate of https://github.com/scalameta/scalafmt/issues/1206 and #1200. The problem is not bloop+scalafmt, the problem is transitive dependencies of sbt.

**Closed by olafurpg** 2018-06-05 15:47 UTC

**Comment by olafurpg** [comment] 2018-06-05 18:45
My bad, this is not a duplicate of #1206 but it is a duplicate of #1200.

**Comment by olafurpg** [comment] 2018-06-11 15:49
Hi, sbt-scalafmt v1.6.0-RC3 is out and this issue should now be resolved. Scalafmt dependencies are now shaded to avoid classpath conflicts with sbt. Please let me know if the issue has resolved
