### ISSUE TITLE
2.3.3-RC1 always crashes with "classpath is corrupted"

### ISSUE THREAD

**Issue by adampauls** [scalameta/scalafmt#1628] opened 2020-01-10 15:29 UTC
I tried upgrading to 2.3.3-RC1 and I always get

 ```[error] scalafmt version 2.3.3-RC1 classpath is corrupted```

I've tried running `sbt clean update` and that did not help. This issue is not present with 2.3.2 so I do not believe it is my setup.

Thanks for the great tool, looking forward to using 2.3.3!

My configuration is:

```
version = "2.3.3-RC1"
maxColumn = 120 
rewrite.rules = [PreferCurlyFors, SortModifiers, AvoidInfix, SortImports]
trailingCommas = always
assumeStandardLibraryStripMargin = true
optIn.breakChainOnFirstMethodDot = false
spaces.inImportCurlyBraces = true
includeCurlyBraceInSelectChains = true
spaces.beforeContextBoundColon = Always
// These are copied from  https://scalameta.org/scalafmt/docs/configuration.html#other
rewrite.neverInfix.excludeFilters = [
  until
  to
  by
  eq
  ne
  "should.*"
  "contain.*"
  "must.*"
  in
  ignore
  be
  taggedAs
  thrownBy
  synchronized
  have
  when
  size
  only
  noneOf
  oneElementOf
  noElementsOf
  atLeastOneElementOf
  atMostOneElementOf
  allElementsOf
  inOrderElementsOf
  theSameElementsAs
  // these are new
  throws
  returns
  satisfy
]
```

**Comment by adampauls** [comment] 2020-01-15 16:28
As a follow-up: I cleaned out my coursier cache and tried again. I also tried limiting concurrency like in https://github.com/scalameta/scalafmt/issues/1399 and only running on a single project. None of it helped :(

**Comment by tanishiking** [comment] 2020-01-16 11:49
@adampauls Thank you for reporting! Which version of sbt scalafmt are you using!
And could you share the stacktrace if possible?

**Comment by poslegm** [comment] 2020-01-16 12:03
@tanishiking It reproduces with Intellij integration. So I guess that it is not sbt-scalafmt problem

**Comment by tanishiking** [comment] 2020-01-16 14:01
Thanks for your input!.
The error comes from `scalafmt-dynamic` [here](https://github.com/scalameta/scalafmt/blob/dee798a99e16dcf32fea37cdc05d694b76647ada/scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamic.scala#L94-L96), and it would be nice to know which version of `scalafmt-dynamic` causes this problem :)

But, it might be better to emit the original error message of `ReflectiveOperationException`:  sbt-scalafmt (v2.3.0) discards the original message of the exception, and we have no clue to tackle this problem.
- https://github.com/scalameta/scalafmt/blob/dee798a99e16dcf32fea37cdc05d694b76647ada/scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamic.scala#L96
- https://github.com/scalameta/scalafmt/blob/dee798a99e16dcf32fea37cdc05d694b76647ada/scalafmt-interfaces/src/main/java/org/scalafmt/interfaces/ScalafmtReporter.java#L29-L39

**Comment by adampauls** [comment] 2020-01-16 15:21
I was using sbt-scalafmt 2.0.2. I just tried upgrading to 2.3.0 (sorry, I forgot that was an option), but that did not resolve the issue.

**Comment by kitbellew** [comment] 2020-01-27 19:22
@tanishiking now that you've merged the `sbt-scalafmt` fix, how do we go forward with this? i don't think we can release 2.3.3 without fixing this, even though i can't reproduce it (as i don't use sbt). any way i can help?

**Comment by tanishiking** [comment] 2020-01-28 04:46
I just cut a new release of sbt-scalafmt v2.3.1, which will show an additional error message for that error.
Could you try it, and share the error message, please? @adampauls 

---

@kitbellew 
Thank you for your comments, unfortunately, that change in `sbt-scalafmt` doesn't fix this problem (it just enable sbt-scalafmt to emit more error messages to get more information to tackle this problem). So it may take more time to fix this.

> i don't think we can release 2.3.3 without fixing this,

I think we can release 2.3.3 without fixing this :) , because

- This problem is a long-existing issue since v2.0.0 (unfortunately)
  - scalafmt works fine for most users.
- this is the problem of scalafmt-dynamic I guess, and the sequence of changes in scalafmt-core are nothing to do with this issue.

Anyway, I hope we can figure out the root problem of this problem...

**Comment by kitbellew** [comment] 2020-01-28 06:12
@tanishiking 

> > i don't think we can release 2.3.3 without fixing this,
> I think we can release 2.3.3 without fixing this :) , because

ah, that's great to hear.

p.s. by the way, what is the process of releasing (apart from tagging a commit)?

**Comment by adampauls** [comment] 2020-01-28 15:50
I tried downloading v2.3.1 of the plugin, but I don't think it's available yet. That said, I want to make clear that the issue does seem to be specific to 2.3.3, even if the bug is in the plugin and not scalafmt itself. Every other version that I've tried works fine for me.

**Comment by kitbellew** [comment] 2020-01-28 16:39
@adampauls have you tried sbt-scalafmt 2.2.1 with formatter 2.3.3-RC2? does sbt-scalafmt 2.3.0 work with formatter 2.3.2 or earlier, for you?

also, how does one specify for a given sbt-scalafmt instance which scalafmt library version should be used? is it just through the config file and dynamic loading?

**Comment by tanishiking** [comment] 2020-01-28 17:47
Oops, sorry I misunderstood the problem. This phenomenon is reproduced even in my environment. If we try to use `2.3.3-RC1` from both `sbt-scalafmt (v2.3.0)` and `scalafmt-cli (v2.3.2)`

<details>
<summary> piece of stacktrace from cli</summary>
```
org.scalafmt.cli.FailedToFormat: /Users/tanishiking/dev/src/github.com/tanishiking/scalafmt/.scalafmt.conf
Caused by: java.lang.RuntimeException: scalafmt version 2.3.3-RC2 classpath is corrupted
        at org.scalafmt.interfaces.ScalafmtReporter.error(ScalafmtReporter.java:38)
        at org.scalafmt.cli.ScalafmtCliReporter.error(ScalafmtCliReporter.scala:15)
        at org.scalafmt.dynamic.ScalafmtDynamic.reportError(ScalafmtDynamic.scala:96)
        at org.scalafmt.dynamic.ScalafmtDynamic.format(ScalafmtDynamic.scala:74)
        at org.scalafmt.cli.ScalafmtDynamicRunner$.handleFile(ScalafmtDynamicRunner.scala:96)
        at org.scalafmt.cli.ScalafmtDynamicRunner$.$anonfun$run$4(ScalafmtDynamicRunner.scala:55)
        at org.scalafmt.cli.ScalafmtDynamicRunner$.$anonfun$run$4$adapted(ScalafmtDynamicRunner.scala:49)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at org.scalafmt.cli.ScalafmtDynamicRunner$.$anonfun$run$3(ScalafmtDynamicRunner.scala:49)
        at scala.util.control.Breaks.breakable(Breaks.scala:42)
        at org.scalafmt.cli.ScalafmtDynamicRunner$.run(ScalafmtDynamicRunner.scala:49)
        at org.scalafmt.cli.Cli$.runWithRunner(Cli.scala:135)
        at org.scalafmt.cli.Cli$.run(Cli.scala:84)
        at org.scalafmt.cli.Cli$.mainWithOptions(Cli.scala:69)
        at org.scalafmt.cli.Cli$.main(Cli.scala:58)
        at org.scalafmt.cli.Cli.main(Cli.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at coursier.bootstrap.launcher.a.a(Unknown Source)
        at coursier.bootstrap.launcher.Launcher.main(Unknown Source)
Caused by: java.lang.NoSuchMethodException: org.scalafmt.Scalafmt.format(java.lang.String, org.scalafmt.config.ScalafmtConfig, scala.collection.immutable.Set)
        at java.lang.Class.getMethod(Class.java:1786)
        at org.scalafmt.dynamic.ScalafmtReflect.<init>(ScalafmtReflect.scala:40)
        at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveClassPath$1(ScalafmtDynamic.scala:188)
        at scala.util.Try$.apply(Try.scala:213)
        at org.scalafmt.dynamic.ScalafmtDynamic.resolveClassPath(ScalafmtDynamic.scala:186)
        at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveFormatter$3(ScalafmtDynamic.scala:177)
        at scala.util.Either.flatMap(Either.scala:341)
        at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveFormatter$1(ScalafmtDynamic.scala:177)
        at scala.util.Try$.apply(Try.scala:213)
        at org.scalafmt.dynamic.utils.ReentrantCache.getOrAddToCache(ReentrantCache.scala:41)
        at org.scalafmt.dynamic.ScalafmtDynamic.resolveFormatter(ScalafmtDynamic.scala:163)
        at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveConfigWithScalafmt$2(ScalafmtDynamic.scala:142)
        at scala.util.Either.flatMap(Either.scala:341)
        at org.scalafmt.dynamic.ScalafmtDynamic.resolveConfigWithScalafmt(ScalafmtDynamic.scala:139)
        at org.scalafmt.dynamic.ScalafmtDynamic.$anonfun$resolveConfig$4(ScalafmtDynamic.scala:125)
        at scala.util.Try$.apply(Try.scala:213)
        at org.scalafmt.dynamic.utils.ReentrantCache.getOrAddToCache(ReentrantCache.scala:41)
        at org.scalafmt.dynamic.ScalafmtDynamic.resolveConfig(ScalafmtDynamic.scala:124)
        at org.scalafmt.dynamic.ScalafmtDynamic.formatDetailed(ScalafmtDynamic.scala:108)
```
</details>

We have to fix this before cutting a new release (2.3.3), but I'm not sure what causes this...

---

@adampauls 
Sorry, the release process for sbt-scalafmt 2.3.1 seemed to fail... I'm gonna check it this weekend.

- https://repo1.maven.org/maven2/org/scalameta/sbt-scalafmt_2.12_1.0/
- https://travis-ci.org/scalameta/sbt-scalafmt/jobs/642724103

---

@kitbellew 
> what is the process of releasing (apart from tagging a commit)

- You can cut a new release from https://github.com/scalameta/scalafmt/releases/new
- since 2.3.3 will have a lot of changes, it's best to write a detailed release note like this https://github.com/scalameta/scalafmt/releases/tag/v2.3.0-RC2

**Comment by kitbellew** [comment] 2020-01-28 19:05
@tanishiking is it possible that i "cut" the two rc releases incorrectly? i didn't do the "releases/new", simply tagged the repo as olafur once suggested.

**Comment by kitbellew** [comment] 2020-01-28 19:30
@tanishiking i will fix shortly. the problem you saw is from https://github.com/scalameta/scalafmt/commit/117477bfe97a70bbd0a75bfc4ea34507dc8579d1

**Comment by poslegm** [comment] 2020-01-28 19:37
@tanishiking 

> Sorry, the release process for sbt-scalafmt 2.3.1 seemed to fail... I'm gonna check it this weekend.

It may be related: https://issues.sonatype.org/browse/OSSRH-34782

**Closed** 2020-01-29 15:19 UTC
Labels: bug

**Comment by tanishiking** [comment] 2020-01-29 15:52
@adampauls 
kitbellew fixed this problem in the latest master https://github.com/scalameta/scalafmt/pull/1654 (thank you!), so this will be fixed in the next release. Thank you for reporting!
