### ISSUE TITLE
No option to keep dot at end of line when chaining methods

### ISSUE THREAD

**Issue by rcano** [scalameta/scalafmt#1411] opened 2019-04-26 01:24 UTC
- **Version**: 0.5

scalafmt forces the method chaining token (the dot) to be at the start of the line. There should be an option to keep it dangling in the previous line.
This is to be consistent with every other chaining syntactical token, like:
parameters chaining token (the comma): 
```
foor(
 a,
 b,
 c,
) 
```
binary operators chaining token (the operator itself):
```
a +
b +
c +
d
```

### Problem
```
a.foo(...)
  .bar(...)
  .baz(...)
```
This is how scalafmt will format with no option to change it.

### Expected
An option that lets it format as in
```
a.foo(...).
  bar(...).
  baz(...)
```

### Workarounds
None known.

**Comment by kitbellew** [comment] 2020-05-11 16:47
@rcano i am afraid that if you contributed a patch implementing this (and adding a new parameter to enable this), it will not likely be accepted.

**Comment by rcano** [comment] 2020-05-11 22:58
> i am afraid that if you contributed a patch implementing this (and adding a new parameter to enable this), it will not likely be accepted.

I don't know what to do with this information :). There's no reason to reject it, unless you know something I don't. The formatter is already full of options for tweaking things contrary to how someone else might like things, but that's what options are for. I don't see why an option for this would be **rejected**; nobody spending time on this, sure, but rejected? sounds a bit harsh.

**Comment by tlazaro** [comment] 2020-05-11 23:27
I would like this option too.

**Comment by kitbellew** [comment] 2020-05-12 00:12
> > i am afraid that if you contributed a patch implementing this (and adding a new parameter to enable this), it will not likely be accepted.
> 
> I don't know what to do with this information :). There's no reason to reject it, unless you know something I don't. The formatter is already full of options for tweaking things contrary to how someone else might like things, but that's what options are for. I don't see why an option for this would be **rejected**; nobody spending time on this, sure, but rejected? sounds a bit harsh.

my apologies :) i saw this ticket here without a reply for a year, and decided to share an opinion on the reason, based on prior observations. so far, the maintainers have been quite ambivalent about adding new parameters (rather than new options for existing parameters), as the number of interactions/conflicts with other parameters is increasing.

of course, if you'd like to contribute a patch and convince @olafurpg and @tanishiking...

**Comment by poslegm** [comment] 2020-05-12 09:37
The problem is that such code style is pretty rare in Scala community. And I am afraid that supporting it in scalafmt will require non-trivial changes which will increase maintaining complexity. 

It may be accepted only if it's easy to implement and easy to support.

**Comment by olafurpg** [comment] 2020-05-12 12:12
I agree with @kitbellew that this option is unlikely to get merged for the same reason Scalafmt doesn't support an option to configure the default 2-space indent in blocks. The "dot at start of line" in select chain formatting convention is widely used in the community.

**Comment by tlazaro** [comment] 2020-05-12 17:27
I used to use that format because it was the way to ensure code copied to the REPL worked without modification. Multi-line expressions or statements should be invalid unless all lines were processed. Hence dangling operators and dots. It also makes layout consistent and has words aligned better.

I stopped using it because of auto-formatting tools (IDEs and external) not supporting it. I rather consistency first, specially in a shared codebase, followed by style details.

I think at this point in how good and widely adopted scalafmt is, the styles seen in the wild are no longer what users would choose but what scalafmt allows.

I can understand having and keeping strong defaults and this not being something you would put time into. But pre-emptively rejecting a PR for adding the option sounds harsh to me.

> I agree with @kitbellew that this option is unlikely to get merged for the same reason Scalafmt doesn't support an option to configure the default 2-space indent in blocks. The "dot at start of line" in select chain formatting convention is widely used in the community.

I understand, but on the other hand there are many other cases where multiple options are available and overall there are a lot of options. It seems arbitrary to forbid this one option.

**Comment by tlazaro** [comment] 2020-05-12 18:03
> The problem is that such code style is pretty rare in Scala community. And I am afraid that supporting it in scalafmt will require non-trivial changes which will increase maintaining complexity.
> 
> It may be accepted only if it's easy to implement and easy to support.

Makes sense, thanks.

**Comment by olafurpg** [comment] 2020-05-12 18:07
> I used to use that format because it was the way to ensure code copied to the REPL worked without modification.

In this particular use-case, you can use the REPL command `:paste` to paste in any code
```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

List(1)
  .map(...)

<ctrl-D>
```

**Comment by poslegm** [comment] 2020-05-12 18:13
Or just use https://ammonite.io

**Comment by poslegm** [comment] 2020-05-12 18:18
> But pre-emptively rejecting a PR for adding the option sounds harsh to me.

IMHO It is better to notify potential contributors before they spend time and effort on a feature that will not be accepted

**Closed** 2021-04-01 11:39 UTC
