### ISSUE TITLE
Fails with FailedToFormat exception out of the box on Debian slim

### ISSUE THREAD

**Issue by bsolomon1124** [scalameta/scalafmt#1828] opened 2020-03-30 12:20 UTC
Following https://scalameta.org/scalafmt/docs/installation.html#native-image:

Dockerfile:

```
FROM debian:stable-slim
ARG VERSION=2.4.2
ARG INSTALL_LOCATION=/usr/local/bin/scalafmt-native
RUN set -ex \
    && apt-get update -y \
    && apt-get install -y --no-install-recommends curl unzip \
    && echo insecure > "$HOME/.curlrc" \
    && curl https://raw.githubusercontent.com/scalameta/scalafmt/master/bin/install-scalafmt-native.sh | \
        sh -s -- $VERSION $INSTALL_LOCATION
```

Invocation:

```
docker container run --rm ^
    --volume C:\Users\myname\dev\project-name:/project-name ^
    scalafmt-test:1 ^
    sh -c "scalafmt-native project-name/path/to/file.scala"
```

Traceback:

```
root@11615410ad72:/# scalafmt-native /project-name/path/to/file.scala
org.scalafmt.cli.FailedToFormat: /project-name/path/to/file.scala
Caused by: java.lang.NoSuchMethodException: org.scalafmt.internal.FormatWriter$$anon$2.last()
        at java.lang.Class.getMethod(DynamicHub.java:1053)
        at org.scalafmt.internal.FormatWriter.reflMethod$Method1(FormatWriter.scala:564)
        at org.scalafmt.internal.FormatWriter.alignmentTokens(FormatWriter.scala:564)
        at org.scalafmt.internal.FormatWriter$FormatLocations.<init>(FormatWriter.scala:258)
        at org.scalafmt.internal.FormatWriter.getFormatLocations(FormatWriter.scala:154)
        at org.scalafmt.internal.FormatWriter.mkString(FormatWriter.scala:26)
        at org.scalafmt.Scalafmt$.formatCode(Scalafmt.scala:73)
        at org.scalafmt.cli.ScalafmtCoreRunner$.unsafeHandleFile(ScalafmtCoreRunner.scala:87)
        at org.scalafmt.cli.ScalafmtCoreRunner$.handleFile(ScalafmtCoreRunner.scala:66)
        at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$3(ScalafmtCoreRunner.scala:44)
        at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$3$adapted(ScalafmtCoreRunner.scala:43)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1274)
        at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:946)
        at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
        at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
        at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
        at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:943)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:152)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:148)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:303)
        at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

**Comment by poslegm** [comment] 2020-03-30 12:30
Hello! Sorry for the inconvenience with native binary.

This issue is a duplicate of https://github.com/scalameta/scalafmt/issues/1769
Will be fixed in the next release. PR with fix: https://github.com/scalameta/scalafmt/pull/1791
Current workaround — [non-native CLI client](https://scalameta.org/scalafmt/docs/installation.html#coursier)

**Closed by poslegm** 2020-03-30 12:30 UTC

**Comment by bsolomon1124** [comment] 2020-03-30 12:39
@poslegm thanks for the quick reply.

I was able to get the [bootstrap script via Coursier](https://scalameta.org/scalafmt/docs/installation.html#coursier) working properly on the same image.
