### ISSUE TITLE
Can I keep curly braces lambdas in one line in map/filter expressions?

### ISSUE THREAD

**Issue by zawistowski** [scalameta/scalafmt#1031] opened 2017-08-21 11:30 UTC
This template is a guideline, not a strict requirement.
- **Version**: 1.0 
- **Integration**: neo scalafmt 1.10, sbt 0.13
- **Configuration**:

```
newlines.alwaysBeforeCurlyBraceLambdaParams = false
runner.optimizer.forceConfigStyleMinArgCount = 6
includeCurlyBraceInSelectChains = false
runner.optimizer.forceConfigStyleOnOffset = 30
optIn.breakChainOnFirstMethodDot = false
maxColumn = 140
```

## Steps

I ran scalafmt like this:

```bash
sbt scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
case t : MyClass => 
  stuff.filter { 
     thing => getValueFromThing(thing, index) >= minimal 
  }
```

## Expectation
  I would like the formatted output to look like this:
```scala
case t : MyClass => stuff.filter { thing => getValueFromThing(thing, index) >= minimal } 
```

## Notes

I want to be able to keep expression such as filter { case x => ... } in one line, since I have many of them and most are very simple (i.e. they are in the beginning and I want scalafmt to just ignore them).  I thought this should be doable with options such as listed but had no success in doing so.
Found some notes about this feature in #444.

**Comment by pjrt** [comment] 2017-08-22 21:51
Seems this is a duplicate of: https://github.com/scalameta/scalafmt/issues/1027

@zawistowski can u confirm? Or do you actually want it to be curly parens?

**Comment by zawistowski** [comment] 2017-08-23 09:34
No, I need curly braces in expressions such as: Map("number" -> 3).map { case(key, value) =>key -> value * 2} (and to keep them in one line).

**Comment by pjrt** [comment] 2017-08-23 11:15
Well if there's a `case` statement we shouldn't turn it into  parens (good catch), however it is the same overall concept. 

Can you add your case example to the other ticket?

**Comment by olafurpg** [comment] 2017-09-07 21:25
Seems like duplicate of #913 Thank you for reporting @zawistowski !

**Closed by olafurpg** 2017-09-07 21:25 UTC
