### ISSUE TITLE
Can't use different version for native CLI

### ISSUE THREAD

**Issue by EnviousSwan** [scalameta/scalafmt#4571] opened 2024-11-20 14:34 UTC
This issue is observable in the following configuration
- latest version of CLI and previous version in `.scalafmt.conf`

## Configuration (required) ##

```hocon
version = 3.8.3
runner.dialect = scala3
...
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = false
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt --diff-branch origin/master`

## Steps

Given a GitHub workflow 
```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: coursier/setup-action@v1
      with:
        jvm: temurin:21
        apps: scalafmt
    - run: scalafmt --diff-branch origin/master
```

## Problem

When running `scalafmt` when a PR is raised via
```
Run scalafmt --diff-branch origin/master
  scalafmt --diff-branch origin/master
  shell: /usr/bin/bash -e {0}
  env:
    JAVA_HOME: /home/runner/.cache/coursier/arc/https/github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.5%252B11/OpenJDK21U-jdk_x64_linux_hotspot_21.0.5_11.tar.gz/jdk-21.0.5+11
    COURSIER_BIN_DIR: /home/runner/cs/bin
```

I get the following error
```
Exception in thread "main" java.lang.Exception: Can't use different version for native CLI
	at org.scalafmt.interfaces.Scalafmt$.create(Scalafmt.scala:142)
	at org.scalafmt.interfaces.Scalafmt.create(Scalafmt.scala)
	at org.scalafmt.cli.ScalafmtDynamicRunner$.run(ScalafmtDynamicRunner.scala:21)
	at org.scalafmt.cli.Cli$.runWithRunner(Cli.scala:134)
	at org.scalafmt.cli.Cli$.run(Cli.scala:61)
	at org.scalafmt.cli.Cli$.mainWithOptions(Cli.scala:35)
	at org.scalafmt.cli.Cli$.main(Cli.scala:18)
	at org.scalafmt.cli.Cli.main(Cli.scala)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at coursier.bootstrap.launcher.a.a(Unknown Source)
	at coursier.bootstrap.launcher.Launcher.main(Unknown Source)
```

## Expectation

I expect `scalafmt` to format the code or just do nothing 
```scala
Run scalafmt --diff-branch origin/master
  scalafmt --diff-branch origin/master
  shell: /usr/bin/bash -e {0}
  env:
    JAVA_HOME: /home/runner/.cache/coursier/arc/https/github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.5%252B11/OpenJDK21U-jdk_x64_linux_hotspot_21.0.5_11.tar.gz/jdk-21.0.5+11
    COURSIER_BIN_DIR: /home/runner/cs/bin
Reformatting...
```

## Workaround

I've found that by setting scalafmt version in `.scalafmt.conf` to the latest `3.4.2-RC2` the issue doesn't happen anymore

## Notes
My assumption is that `coursier` pulls the latest `scalafmt-cli` as it's configured to [latest.release](https://github.com/coursier/apps/blob/2b04d1e06bacbc7f71e185dc06e45aefc9b7aee5/apps/resources/scalafmt.json#L6-L8)

This only started happening yesterday, probably after `3.8.4-RC2` release, because there were no problems when `3.8.4-RC1` was the latest.

The same issue happens when running scala-steward from GitHub Actions when it tries to reformat changes
```
 2024-11-20 09:05:57,595 INFO  Found 1 update:
    io.github.embeddedkafka:(embedded-kafka, embedded-kafka_2.13) : 3.8.1 -> 3.9.0
  2024-11-20 09:05:57,599 INFO  Process update io.github.embeddedkafka:(embedded-kafka, embedded-kafka_2.13) : 3.8.1 -> 3.9.0
  2024-11-20 09:05:57,833 INFO  Create branch update/embedded-kafka-3.9.0
  2024-11-20 09:05:58,814 WARN  Reformatting changed files failed in .
  org.scalasteward.core.io.process$ProcessFailedException: '"SBT_OPTS=-Xmx2048m -Xss8m -XX:MaxMetaspaceSize=512m" scalafmt --non-interactive --mode changed' exited with code 1.
  Error: Exception in thread "main" java.lang.Exception: Can't use different version for native CLI
  	at org.scalafmt.interfaces.Scalafmt$.create(Scalafmt.scala:142)
  	at org.scalafmt.interfaces.Scalafmt.create(Scalafmt.scala)
```

**Comment by EnviousSwan** [comment] 2024-11-20 14:40
Can confirm this happens locally when it's `3.8.3` or `3.8.4-RC1` in `.scalafmt.conf`

```
scalafmt --version
✔ scalafmt 3.8.4-RC2      
                                                                                                                                                                                      
scalafmt                                                                                                                                 
✔ Exception in thread "main" java.lang.Exception: Can't use different version for native CLI
        at org.scalafmt.interfaces.Scalafmt$.create(Scalafmt.scala:142)
        at org.scalafmt.interfaces.Scalafmt.create(Scalafmt.scala)
        at org.scalafmt.cli.ScalafmtDynamicRunner$.run(ScalafmtDynamicRunner.scala:21)
        at org.scalafmt.cli.Cli$.runWithRunner(Cli.scala:134)
        at org.scalafmt.cli.Cli$.run(Cli.scala:61)
        at org.scalafmt.cli.Cli$.mainWithOptions(Cli.scala:35)
        at org.scalafmt.cli.Cli$.main(Cli.scala:18)
        at org.scalafmt.cli.Cli.main(Cli.scala)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at coursier.bootstrap.launcher.a.a(Unknown Source)
        at coursier.bootstrap.launcher.Launcher.main(Unknown Source)
```

**Comment by kitbellew** [comment] 2024-11-20 15:23
@EnviousSwan why are you submitting this issue here, and not to the maintainer of `coursier/setup-action@v1`?

judging by the error message, that setup-action downloaded a native binary rather than a JVM, and native does not allow the `version` line in `.scalafmt.conf` to be different from the actual version of the binary.

**Comment by tgodzik** [comment] 2024-11-20 15:54
Looks like it's not actually native image but a bootstrapped jar, so should work.

**Comment by kitbellew** [comment] 2024-11-20 15:59
it appears that @jchyb 's #4325 is not fully ready. let me see what i can do to fix, without a full-blown revert.

**Comment by kitbellew** [comment] 2024-11-20 17:09
@alexarchambault is it possible that coursier downloads a native version, instead of jvm, if one is available, like for [3.8.4-RC2](https://mvnrepository.com/artifact/org.scalameta/scalafmt-cli)?

judging by the error message ("Can't use different version for native CLI"), it comes from the NativePlatform build, and not the JVMPlatform version.

I just downloaded two versions, both of them produce this "Can't use" error:
- `coursier bootstrap org.scalameta:scalafmt-cli_2.13:3.8.4-RC2 -r sonatype:snapshots --main org.scalafmt.cli.Cli   --standalone`
- `coursier bootstrap org.scalameta:scalafmt-cli_2.13:3.8.4-RC2 -r sonatype:snapshots --main org.scalafmt.cli.Cli`

Yet I added a #4572 test, and both JVM and Native version seem to load the right interface.

@tgodzik @jchyb any other ideas?

**Comment by jchyb** [comment] 2024-11-20 17:19
It's weird, I tried to run the locally released assembly version and that works fine, but launching the RC from coursier indeed reproduces the error. I have a suspicion about the `crossVersion := CrossVersion.disabled` (perhaps it leads set to ignore the `native` and `jvm` directory split?) line in the build.sbt, but not sure how to test removing it

**Comment by tgodzik** [comment] 2024-11-20 17:21
On the other hand `3.8.4-RC1` works and it also has native artifacts released.

**Comment by tgodzik** [comment] 2024-11-20 17:26
Could it be an issue that it's under `java`> https://github.com/scalameta/scalafmt/blob/a29aa8ada21587d2c9770932269897b2e1c6489a/scalafmt-interfaces/native/src/main/java/org/scalafmt/interfaces/Scalafmt.scala#L142

**Comment by tgodzik** [comment] 2024-11-20 17:36
Looks like both interfaces and interfacesNative publish the same jars, which is why this is random.

**Closed** 2024-11-20 18:28 UTC

**Comment by joan38** [comment] 2024-11-20 20:31
What action can we take to unblock https://github.com/scala-steward-org/scala-steward/pull/3481 ?

**Comment by kitbellew** [comment] 2024-11-20 20:44
> What action can we take to unblock [scala-steward-org/scala-steward#3481](https://github.com/scala-steward-org/scala-steward/pull/3481) ?

use an older formatter version, i think.

**Comment by joan38** [comment] 2024-11-20 21:18
Arf I think our test is actually trying to upgrade to the latest. So we are blocked until a release with the fix is out.

**Comment by kitbellew** [comment] 2024-11-20 21:25
> Arf I think our test is actually trying to upgrade to the latest. So we are blocked until a release with the fix is out.

in that case, give us please a couple of days.

**Comment by joan38** [comment] 2024-11-21 03:35
I was able to cap the version upgrade. No rush guys.
Thanks for the awesome work!
