### ISSUE TITLE
scalafmt is not compatible with scalameta 3+

### ISSUE THREAD

**Issue by pshirshov** [scalameta/scalafmt#1118] opened 2018-03-03 19:04 UTC
Do you have any plans to port the library to 3.+?

RN it is failing on `import scala.meta.inputs.Input`:

`Missing class: scala/meta/inputs/Input
java.lang.NoClassDefFoundError: scala/meta/inputs/Input`

**Comment by olafurpg** [comment] 2018-03-03 20:38
Duplicate of #975. This is a known issue, it's not clear when we'll be able to upgrade.

**Closed by olafurpg** 2018-03-03 20:38 UTC
