### ISSUE TITLE
Annoing "error: expected class or object definition" on files like .gitignore, .scalafmt.conf

### ISSUE THREAD

**Issue by svitovyda** [scalameta/scalafmt#1444] opened 2019-07-01 14:09 UTC
- **Version**: 2.0.0-RC8

I wrote the pre-commit git hook, that gets the list of files to commit and runs scalafmt only on those files and aborts the commit only when commit files were changed:

```
scala_files_to_commit=`git diff-index --cached --name-only HEAD`
scalafmt --git true $scala_files_to_commit
scala_files_modified="$(git diff --name-only)"
```

So I assume by passing files as a list, I enforce the tool to go over the files it would ignore otherwise. Can this be avoided?

Also, if I turn `--exclude` option to ignore those files, I often get ```"No files formatted/tested. Verify include/exclude filters and command line arguments."```

I saw the issue where this error was implemented, but in my case it is just annoying noise. Can there be a flag to ignore this empty files list error enforcement?

**Comment by tanishiking** [comment] 2019-07-06 09:54
@svitovyda Thank you for reporting!
Unfortunately, scalafmt-cli tries to format all the files we specified in the arguments, (see: https://github.com/scalameta/scalafmt/blob/e3d7dd355f3a3838d9738d0c3b82ec3da2367b18/scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtRunner.scala#L63-L67) this is intended behavior,

Alternatively, scalafmt has `--diff` option that makes scalafmt-cli try to format only files that have diff (that seems scala programs).
The git hook configuration for scalameta/metals may help you :)
https://github.com/olafurpg/metals/blob/acbd168661650e93af4615d876e32d0a59f1962a/build.sbt#L103-L113

**Comment by tanishiking** [comment] 2019-07-15 10:06
Let me close this issue for now, if you have any problems on scalafmt-cli, please re-open this :)

**Closed by tanishiking** 2019-07-15 10:06 UTC
