### ISSUE TITLE
scalafmtCheck not accepting formatted code

### ISSUE THREAD

**Issue by fdietze** [scalameta/scalafmt#1231] opened 2018-06-29 09:14 UTC
```scala
addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "1.6.0-RC3")
```
(default configuration)

In my sbt project I have several (heavily reduced) scala-files. When I run `scalafmt` and then `scalafmtCheck`, These files get reported as not being properly formatted. The second one only gets reported after the first one is changed to be properly formatted.

```scala
object MainViewParts {

  val syncModeSwitcher =
    span(
      state.syncMode
        .map {
          mode =>
            span(
              title := "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
              onClick
                .map(
                  _ =>
                    (if (mode == SyncMode.Live) SyncMode.Local
                     else SyncMode.Live): SyncMode
                ) --> state.syncMode
            )
        }
    )

}
```
Shortening the string makes this one work.

```scala
object TestView extends View {
  override def apply() = {
    div(
      div(
        (5 to 5).map { res => 5},
        //
      )
    )
  }
}
```
Removing the comment makes this one work.

```scala
object ViewConfigParser {
  val page: P[Page] = P( pageMode ~/ (pageSeparator ~/ nodeIdList ~ (pageSeparator ~ nodeIdList).?).? ~/ (urlSeparator | End) )
    .map {
      case x => Page()
    }
}
```

Do you need more examples?

**Comment by olafurpg** [comment] 2018-07-02 07:01
Thanks for reporting! I am unable to reproduce, I tried both with the cli and sbt plugin. 

Can you please update https://github.com/olafurpg/repro-scalafmt/blob/master/src/main/scala/Issue1231.scala with an input that reproduces the issue?

**Comment by fdietze** [comment] 2018-07-02 09:42
This was hard to find out: running `scalafmt` a second time in the same sbt session doesn't do anything.

When running it twice in different sbt sessions, my whole project passes the checks.

**Comment by tanishiking** [comment] 2018-10-14 17:36
I took a stub at this issue and found that these regressions are caused by idempotency violations.

> When running it twice in different sbt sessions, my whole project passes the checks.

The cause of this phenomenon is an idempotency violation and sbt.
Since sbt seems cache the `unmanagedSources in scalafmt` in a same session, `scalafmtCheck` after running `scalafmt` twice in a same sbt session will fail because of idempotency violation.
(On the other hand, we can pass `scalafmtCheck` [after we run scalafmt twice in the different sbt sessions](https://github.com/olafurpg/repro-scalafmt/blob/15f2cc018ff939c9a1f2147136b1e805b74a3aa2/repro.sh#L2-L3) )

---

By the way, I tried to fix the violations reported in https://github.com/scalameta/scalafmt/issues/1231#issue-336924066

- [ ] `object MainViewParts { ...`
  - I couldn't reproduce this...
- [x] `object TestView extends View { ... `
  - I found that this was caused by https://github.com/scalameta/scalafmt/issues/1254 and has been fixed in https://github.com/scalameta/scalafmt/pull/1262
  - I added a test https://github.com/scalameta/scalafmt/pull/1296
- [ ] `object ViewConfigParser { ... `
  - I added the following test 

```
<<< test
object ViewConfigParser {
  val page: P[Page] = P( pageMode ~/ (pageSeparator ~/ nodeIdList ~ (pageSeparator ~ nodeIdList).?).? ~/ (urlSeparator | End) ).
  map {
    case x => Page()
  }
}
>>>
object ViewConfigParser {
  val page: P[Page] =
    P(pageMode ~/ (pageSeparator ~/ nodeIdList ~ (pageSeparator ~ nodeIdList).?).? ~/ (urlSeparator | End))
      .map {
        case x => Page()
      }
}
```

and got the following diff

```
[info] - newdefault/ColumnWidth.stat: test                                     | *** FAILED ***
[info]   Idempotency violated
[info]
[info]   ===========
[info]   => Obtained
[info]   ===========
[info]   object ViewConfigParser {
[info]     val page: P[Page] = P(
[info]       pageMode ~/ (pageSeparator ~/ nodeIdList ~ (pageSeparator ~ nodeIdList).?).? ~/ (urlSeparator | End)
[info]     ).map {
[info]       case x => Page()
[info]     }
[info]   }
[info]
[info]
[info]   =======
[info]   => Diff
[info]   =======
[info]      ).map {
[info]   -    case x => Page()
[info]   -  }
[info]   +      case x => Page()
[info]   +    }
[info]    } (FormatTests.scala:79)
```

I know the redundant indentations are caused by https://github.com/scalameta/scalafmt/blob/eae26c94bfed6228f687221af12b82d43c722787/scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala#L697 (indentation for `P( ... )` which has too long columns add redundant indentation indentation on `case x => Page()` and `}`), but the logic for caluculating the indentation is too complicated for me to fix the idempotency violation without breaking other test cases...
As https://github.com/scalameta/scalafmt/pull/1278#pullrequestreview-157940683, we may we want to invest our efforts in https://github.com/scalameta/scalafmt/issues/917

**Comment by joan38** [comment] 2019-02-11 16:43
@dwijnand 2.0.0-RC4 of what?

**Comment by dwijnand** [comment] 2019-02-11 16:47
Scalafmt

**Comment by joan38** [comment] 2019-03-07 06:09
Indeed I didn't notice that 2.x RC serie was out.
Anybody knows if it's fixed?

**Comment by Krever** [comment] 2019-05-30 07:52
I just run into it with plugin in version `2.0.0` and `version = "2.0.0-RC6"` in conf file. Gladly executing `clean` solved the issue.

**Comment by poslegm** [comment] 2019-11-08 16:56
Is it still actual? I can't reproduce

**Comment by fdietze** [comment] 2020-02-04 19:30
Not sure, I'm not using scalafmt at the moment. And if you can't reproduce, it might be a sign that this issue is fixed. :)

**Closed** 2020-02-05 17:06 UTC
Labels: help wanted, regression
