### ISSUE TITLE
Rewrite rules don't respect `// format: off`

### ISSUE THREAD

**Issue by diego-alvarez-hs** [scalameta/scalafmt#932] opened 2017-05-17 18:36 UTC
- **Version**: 0.6.6 and 0.6.8
- **Integration**: bash
- **Configuration**:
```
maxColumn = 100
```

## Steps

I ran scalafmt like this:

```bash
scalafmt -f File.scala --config=/Users/diegoa/.scalafmt.conf -i --exclude ensime
```

## Problem

Scalafmt formats code like this:
```scala
  val x = {
    // format: off
    implicit val reads: Reads[MessageTemplate] = (
      (__ \ "a").read[String] .and        ((__ \ "b").readNullable[Seq[LinkSetting]])
    ) ((s: String, b: Option[Seq[LinkSetting]]) => A(a, b))
    // format: on
    1
  }
```

## Expectation

I would like the formatted output to look like this:
```scala
   val x = {
    // format: off
    implicit val reads: Reads[MessageTemplate] = (
      (__ \ "a").read[String] and
        (__ \ "b").readNullable[Seq[LinkSetting]]
    ) ((s: String, b: Option[Seq[LinkSetting]]) => A(a, b))
    // format: on
    1
  }
```

## Workaround

No workaround

**Comment by diego-alvarez-hs** [comment] 2017-05-17 18:50
somehow the line break is removed

**Comment by diego-alvarez-hs** [comment] 2017-05-17 21:18
As I commented to @pjrt on gitter.
When using `scalafmt -f file` with no additional parameters, it's working fine fine (off/on works)
when using `scalafmt -f file --config=xx` off/on don't work

**Comment by pjrt** [comment] 2017-05-17 21:30
That's odd, there must be some Router case where passing `--config` breaks the format-on/off case.

**Comment by diego-alvarez-hs** [comment] 2017-05-17 21:42
yup,
this is my current config:
```
# options in https://github.com/olafurpg/scalafmt/blob/master/core/src/main/scala/org/scalafmt/config/Settings.scala
style = IntelliJ
align.mixedOwners = false
align.openParenCallSite = false
align.openParenDefnSite = false
align.tokens = ["%", "%%"]
# align.tokens = ["%", "%%", "="] # enable this to format SBT files
binPack.literalArgumentLists = true
binPack.parentConstructors = false
binPackImportSelectors = true
continuationIndent.callSite = 2
continuationIndent.defnSite = 2
continuationIndent.extendSite = 2
danglingParentheses = true
optIn.configStyleArguments = false # has to be false to make danglingParentheses work
docstrings = ScalaDoc
project.git = true
importSelectors = singleLine
includeCurlyBraceInSelectChains = false
indent.rightAssociativeInfixOperatorsLikeLeftAssociative = true
# indentOperator.exclude = "^(::|&&|\\|\\|)$"
maxColumn = 110
newlines.alwaysBeforeCurlyBraceLambdaParams = false
newlines.alwaysBeforeTopLevelStatements = true
newlines.penalizeSingleSelectMultiArgList = false
newlines.sometimesBeforeColonInMethodReturnType = false
optIn.annotationNewlines = true
optIn.breakChainOnFirstMethodDot = false
rewrite.rules = [AsciiSortImports, AvoidInfix, PreferCurlyFors, RedundantBraces, RedundantParens]
rewrite.redundantBraces.stringInterpolation = true
spaces.inImportCurlyBraces = false
unindentTopLevelOperators = true

```

**Comment by olafurpg** [comment] 2017-05-17 22:33
Thank you for reporting! This sounds like a bug in the cli. I'm on my phone atm but I can try to take a look on my laptop tomorrow.

**Comment by olafurpg** [comment] 2017-05-18 09:59
This is caused by the combination of `AvoidInfix` rewrite and `// format: off`. The rewrite is executed inside ranges where formatting is disabled. Rewrites make the minimal required diff, and scalafmt takes care of formatting it nicely. 

We should probably skip rewrites inside `// format: off` ranges. That should be doable around here https://github.com/scalameta/scalafmt/blob/ba319e0aaee6d4e1b30098ad57940c67910c33e9/scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/Patch.scala#L50 by filtering out patches inside disabled ranges.

A workaround for now is to manually format the output of the rewrite

```scala
// format: off
    implicit val reads: Reads[MessageTemplate] = (
      (__ \ "a").read[String] .and        ((__ \ "b").readNullable[Seq[LinkSetting]])
    ) ((s: String, b: Option[Seq[LinkSetting]]) => A(a, b))
    // format: on
```

**Comment by diego-alvarez-hs** [comment] 2017-05-18 19:25
I also found that adding `add` to the exclusion list help a little bit to keep the format
```
rewrite.neverInfix.excludeFilters = [
  "contain.*"
  "must.*"
  "should.*"
  and
  be
  by
  eq
  have
  in
  ne
  synchronized
  taggedAs
  thrownBy
  to
  until
  when
]
```

**Comment by olafurpg** [comment] 2017-05-19 07:53
Yes, that is also another possible workaround. And it might make the `// format: off` unnecessary in the first place :)

**Comment by olafurpg** [comment] 2018-05-13 23:44
Scalafix has support to disable rules across ranges via it's suppression mechanism `@SuppressWarnings("...")` and `// scalafix:off ..`. Now that scalafmt is on the same scalameta version as scalafix thanks to #1170 it might be worth migrating the custom rewrite framework in scalafmt to scalafix. However, this will not a priority of mine in at least the coming year so I propose to close this ticket. Please reopen if you'd like to work on this, but beware I estimate it's at least several days of work 😉

**Closed by olafurpg** 2018-05-13 23:44 UTC
Labels: bug
