### ISSUE TITLE
Keep visual separation of class/object declaration from implementation

### ISSUE THREAD

**Issue by arbitrary-dev** [scalameta/scalafmt#2242] opened 2020-10-27 18:49 UTC
**Configuration**:
```
version = "2.7.5"

preset = IntelliJ
maxColumn = 110
trailingCommas = multiple

align.preset = some
continuationIndent.extendSite = 2
docstrings.blankFirstLine = yes
indentOperator.exclude = "^(&&|\\|\\||~)$"
newlines.source = keep
newlines.implicitParamListModifierPrefer = after
spaces.beforeContextBoundColon = always
verticalMultiline.atDefnSite = true
verticalMultiline.arityThreshold = 3
verticalMultiline.excludeDanglingParens = []
verticalMultiline.newlineAfterOpenParen = true

rewrite.rules = [
  SortImports,
  RedundantBraces,
  RedundantParens,
  SortModifiers,
]
rewrite.redundantBraces.stringInterpolation = true
```

## Problem

Scalafmt formats code like this:
```diff

-private class Impl(provider: Provider)(
-  implicit ec: ExecutionContext,
-) extends Initializer {
+private class Impl(provider: Provider)(implicit ec: ExecutionContext)
+  extends Initializer {
   override def initialize(
```

So `extends` & `override def` end up being on the same indentation level and right next to each other.
Visual separation (previosly provided by a closing parenthesis on a separate indentation level) is now lost in this mess.

## Expectation

I would like the formatted output to have a newline added, as suggested by [the official style guide](https://docs.scala-lang.org/style/declarations.html):

>empty line should be added to further separate extensions from class implementation

```diff

-private class Impl(provider: Provider)(
-  implicit ec: ExecutionContext,
-) extends Initializer {
+private class Impl(provider: Provider)(implicit ec: ExecutionContext)
+  extends Initializer {
+
   override def initialize(
```

**Comment by kitbellew** [comment] 2020-10-27 23:43
duplicate of #1975

**Closed by kitbellew** 2020-10-27 23:43 UTC
